// --- TRIVIA DATASETS ---
export const CATEGORIES = {
  all_time_scores: [ // Instrumental scores only. No lyrical songs. Max 3 per film.
    // --- John Williams ---
    { title: "The Imperial March", artist: "John Williams", movie: "The Empire Strikes Back", year: 1980 },
    { title: "Main Title", artist: "John Williams", movie: "Star Wars: A New Hope", year: 1977 },
    { title: "Duel of the Fates", artist: "John Williams", movie: "Star Wars: The Phantom Menace", year: 1999 },
    { title: "Hedwig's Theme", artist: "John Williams", movie: "Harry Potter and the Sorcerer's Stone", year: 2001 },
    { title: "Harry's Wondrous World", artist: "John Williams", movie: "Harry Potter and the Sorcerer's Stone", year: 2001 },
    { title: "Theme from Jurassic Park", artist: "John Williams", movie: "Jurassic Park", year: 1993 },
    { title: "Journey to the Island", artist: "John Williams", movie: "Jurassic Park", year: 1993 },
    { title: "Theme from Schindler's List", artist: "John Williams", movie: "Schindler's List", year: 1993 },
    { title: "Raiders March", artist: "John Williams", movie: "Raiders of the Lost Ark", year: 1981 },
    { title: "The Map Room: Dawn", artist: "John Williams", movie: "Raiders of the Lost Ark", year: 1981 },
    { title: "Flying Theme", artist: "John Williams", movie: "E.T. the Extra-Terrestrial", year: 1982 },
    { title: "Superman March", artist: "John Williams", movie: "Superman", year: 1978 },
    { title: "Jaws Theme", artist: "John Williams", movie: "Jaws", year: 1975 },
    { title: "Hymn to the Fallen", artist: "John Williams", movie: "Saving Private Ryan", year: 1998 },
    { title: "Somewhere in My Memory", artist: "John Williams", movie: "Home Alone", year: 1990 },
    { title: "Olympic Fanfare and Theme", artist: "John Williams", movie: "1984 Summer Olympics", year: 1984 },
    { title: "Close Encounters of the Third Kind", artist: "John Williams", movie: "Close Encounters of the Third Kind", year: 1977 },
    
    // --- Hans Zimmer ---
    { title: "Time", artist: "Hans Zimmer", movie: "Inception", year: 2010 },
    { title: "Dream Is Collapsing", artist: "Hans Zimmer", movie: "Inception", year: 2010 },
    { title: "Cornfield Chase", artist: "Hans Zimmer", movie: "Interstellar", year: 2014 },
    { title: "No Time for Caution", artist: "Hans Zimmer", movie: "Interstellar", year: 2014 },
    { title: "The Dark Knight Theme", artist: "Hans Zimmer", movie: "The Dark Knight", year: 2008 },
    { title: "Gladiator Suite", artist: "Hans Zimmer", movie: "Gladiator", year: 2000 },
    { title: "Now We Are Free", artist: "Hans Zimmer", movie: "Gladiator", year: 2000 },
    { title: "Chevaliers de Sangreal", artist: "Hans Zimmer", movie: "The Da Vinci Code", year: 2006 },
    { title: "Discombobulate", artist: "Hans Zimmer", movie: "Sherlock Holmes", year: 2009 },
    { title: "Driving Miss Daisy", artist: "Hans Zimmer", movie: "Driving Miss Daisy", year: 1989 },
    { title: "Paul's Dream", artist: "Hans Zimmer", movie: "Dune", year: 2021 },
    { title: "You're So Cool", artist: "Hans Zimmer", movie: "True Romance", year: 1993 },
    { title: "Lost but Won", artist: "Hans Zimmer", movie: "Rush", year: 2013 },

    // --- Ennio Morricone ---
    { title: "The Good, the Bad and the Ugly", artist: "Ennio Morricone", movie: "The Good, the Bad and the Ugly", year: 1966 },
    { title: "The Ecstasy of Gold", artist: "Ennio Morricone", movie: "The Good, the Bad and the Ugly", year: 1966 },
    { title: "Gabriel's Oboe", artist: "Ennio Morricone", movie: "The Mission", year: 1986 },
    { title: "On Earth As It Is In Heaven", artist: "Ennio Morricone", movie: "The Mission", year: 1986 },
    { title: "Cinema Paradiso", artist: "Ennio Morricone", movie: "Cinema Paradiso", year: 1988 },
    { title: "Love Theme", artist: "Ennio Morricone", movie: "Cinema Paradiso", year: 1988 },
    { title: "Chi Mai", artist: "Ennio Morricone", movie: "Le Professionnel", year: 1981 },
    { title: "L'Arena", artist: "Ennio Morricone", movie: "Kill Bill: Vol. 2", year: 2004 },

    // --- John Barry ---
    { title: "John Dunbar Theme", artist: "John Barry", movie: "Dances with Wolves", year: 1990 },
    { title: "Out of Africa", artist: "John Barry", movie: "Out of Africa", year: 1985 },
    { title: "On Her Majesty's Secret Service", artist: "John Barry", movie: "On Her Majesty's Secret Service", year: 1969 },
    { title: "Midnight Cowboy", artist: "John Barry", movie: "Midnight Cowboy", year: 1969 },
    { title: "Somewhere in Time", artist: "John Barry", movie: "Somewhere in Time", year: 1980 },

    // --- Jerry Goldsmith ---
    { title: "Ave Satani", artist: "Jerry Goldsmith", movie: "The Omen", year: 1976 },
    { title: "Chinatown Theme", artist: "Jerry Goldsmith", movie: "Chinatown", year: 1974 },
    { title: "The Hunt", artist: "Jerry Goldsmith", movie: "Planet of the Apes", year: 1968 },
    { title: "Star Trek: The Motion Picture", artist: "Jerry Goldsmith", movie: "Star Trek: The Motion Picture", year: 1979 },
    { title: "Carol Anne's Theme", artist: "Jerry Goldsmith", movie: "Poltergeist", year: 1982 },

    // --- Howard Shore ---
    { title: "Concerning Hobbits", artist: "Howard Shore", movie: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
    { title: "The Bridge of Khazad Dum", artist: "Howard Shore", movie: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
    { title: "Rohan", artist: "Howard Shore", movie: "The Lord of the Rings: The Two Towers", year: 2002 },
    { title: "The Lighting of the Beacons", artist: "Howard Shore", movie: "The Lord of the Rings: The Return of the King", year: 2003 },

    // --- Alan Silvestri ---
    { title: "Feather Theme", artist: "Alan Silvestri", movie: "Forrest Gump", year: 1994 },
    { title: "Run Forrest Run", artist: "Alan Silvestri", movie: "Forrest Gump", year: 1994 },
    { title: "Back to the Future", artist: "Alan Silvestri", movie: "Back to the Future", year: 1985 },
    { title: "The Avengers", artist: "Alan Silvestri", movie: "The Avengers", year: 2012 },
    { title: "Portals", artist: "Alan Silvestri", movie: "Avengers: Endgame", year: 2019 },
    { title: "Predator Theme", artist: "Alan Silvestri", movie: "Predator", year: 1987 },

    // --- James Horner ---
    { title: "Hymn to the Sea", artist: "James Horner", movie: "Titanic", year: 1997 },
    { title: "Rose", artist: "James Horner", movie: "Titanic", year: 1997 },
    { title: "Braveheart Theme", artist: "James Horner", movie: "Braveheart", year: 1995 },
    { title: "The Ludlows", artist: "James Horner", movie: "Legends of the Fall", year: 1994 },
    { title: "Becoming one of The People", artist: "James Horner", movie: "Avatar", year: 2009 },
    { title: "A Beautiful Mind", artist: "James Horner", movie: "A Beautiful Mind", year: 2001 },
    { title: "Apollo 13 Theme", artist: "James Horner", movie: "Apollo 13", year: 1995 },

    // --- Danny Elfman ---
    { title: "Spider-Man Main Title", artist: "Danny Elfman", movie: "Spider-Man", year: 2002 },
    { title: "Batman Theme", artist: "Danny Elfman", movie: "Batman", year: 1989 },
    { title: "Ice Dance", artist: "Danny Elfman", movie: "Edward Scissorhands", year: 1990 },
    { title: "Introduction", artist: "Danny Elfman", movie: "Edward Scissorhands", year: 1990 },
    { title: "Breakfast Machine", artist: "Danny Elfman", movie: "Pee-wee's Big Adventure", year: 1985 },
    { title: "Beetlejuice Theme", artist: "Danny Elfman", movie: "Beetlejuice", year: 1988 },
    { title: "Men in Black", artist: "Danny Elfman", movie: "Men in Black", year: 1997 },
    { title: "Alice's Theme", artist: "Danny Elfman", movie: "Alice in Wonderland", year: 2010 },

    // --- Vangelis ---
    { title: "Chariots of Fire", artist: "Vangelis", movie: "Chariots of Fire", year: 1981 },
    { title: "Blade Runner Blues", artist: "Vangelis", movie: "Blade Runner", year: 1982 },
    { title: "Tears in Rain", artist: "Vangelis", movie: "Blade Runner", year: 1982 },
    { title: "Conquest of Paradise", artist: "Vangelis", movie: "1492: Conquest of Paradise", year: 1992 },

    // --- Classics & Others ---
    { title: "The Godfather Waltz", artist: "Nino Rota", movie: "The Godfather", year: 1972 },
    { title: "Love Theme", artist: "Nino Rota", movie: "The Godfather", year: 1972 },
    { title: "Love Theme from Romeo and Juliet", artist: "Nino Rota", movie: "Romeo and Juliet", year: 1968 },
    { title: "Tara's Theme", artist: "Max Steiner", movie: "Gone with the Wind", year: 1939 },
    { title: "Theme from A Summer Place", artist: "Percy Faith", movie: "A Summer Place", year: 1959 },
    { title: "The Pink Panther Theme", artist: "Henry Mancini", movie: "The Pink Panther", year: 1963 },
    { title: "Baby Elephant Walk", artist: "Henry Mancini", movie: "Hatari!", year: 1962 },
    { title: "Psycho (The Murder)", artist: "Bernard Herrmann", movie: "Psycho", year: 1960 },
    { title: "Vertigo Prelude", artist: "Bernard Herrmann", movie: "Vertigo", year: 1958 },
    { title: "Taxi Driver Theme", artist: "Bernard Herrmann", movie: "Taxi Driver", year: 1976 },
    { title: "North by Northwest Overture", artist: "Bernard Herrmann", movie: "North by Northwest", year: 1959 },
    { title: "Also Sprach Zarathustra", artist: "Richard Strauss", movie: "2001: A Space Odyssey", year: 1968 },
    { title: "The Magnificent Seven", artist: "Elmer Bernstein", movie: "The Magnificent Seven", year: 1960 },
    { title: "The Great Escape", artist: "Elmer Bernstein", movie: "The Great Escape", year: 1963 },
    { title: "To Kill a Mockingbird", artist: "Elmer Bernstein", movie: "To Kill a Mockingbird", year: 1962 },
    { title: "Halloween Theme", artist: "John Carpenter", movie: "Halloween", year: 1978 },
    { title: "Escape from New York", artist: "John Carpenter", movie: "Escape from New York", year: 1981 },
    { title: "Tubular Bells", artist: "Mike Oldfield", movie: "The Exorcist", year: 1973 },
    { title: "Mission: Impossible", artist: "Lalo Schifrin", movie: "Mission: Impossible", year: 1996 },
    { title: "007 Theme", artist: "Monty Norman", movie: "Dr. No", year: 1962 },
    { title: "Rocky's Reward", artist: "Bill Conti", movie: "Rocky", year: 1976 },
    { title: "Going the Distance", artist: "Bill Conti", movie: "Rocky", year: 1976 },
    { title: "The Right Stuff", artist: "Bill Conti", movie: "The Right Stuff", year: 1983 },
    { title: "Lawrence of Arabia Overture", artist: "Maurice Jarre", movie: "Lawrence of Arabia", year: 1962 },
    { title: "Lara's Theme", artist: "Maurice Jarre", movie: "Doctor Zhivago", year: 1965 },
    { title: "Axel F", artist: "Harold Faltermeyer", movie: "Beverly Hills Cop", year: 1984 },
    { title: "Top Gun Anthem", artist: "Harold Faltermeyer", movie: "Top Gun", year: 1986 },
    { title: "Terminator Theme", artist: "Brad Fiedel", movie: "The Terminator", year: 1984 },
    { title: "RoboCop Theme", artist: "Basil Poledouris", movie: "RoboCop", year: 1987 },
    { title: "Anvil of Crom", artist: "Basil Poledouris", movie: "Conan the Barbarian", year: 1982 },
    { title: "Hymn to Red October", artist: "Basil Poledouris", movie: "The Hunt for Red October", year: 1990 },
    { title: "Merry-Go-Round of Life", artist: "Joe Hisaishi", movie: "Howl's Moving Castle", year: 2004 },
    { title: "One Summer's Day", artist: "Joe Hisaishi", movie: "Spirited Away", year: 2001 },
    { title: "Path of the Wind", artist: "Joe Hisaishi", movie: "My Neighbor Totoro", year: 1988 },
    { title: "Legend of Ashitaka", artist: "Joe Hisaishi", movie: "Princess Mononoke", year: 1997 },
    { title: "He's a Pirate", artist: "Klaus Badelt", movie: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003 },
    { title: "The Black Pearl", artist: "Klaus Badelt", movie: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003 },
    { title: "Mia and Sebastian's Theme", artist: "Justin Hurwitz", movie: "La La Land", year: 2016 },
    { title: "Planetarium", artist: "Justin Hurwitz", movie: "La La Land", year: 2016 },
    { title: "Married Life", artist: "Michael Giacchino", movie: "Up", year: 2009 },
    { title: "Life's Incredible Again", artist: "Michael Giacchino", movie: "The Incredibles", year: 2004 },
    { title: "Star Trek Main Theme", artist: "Michael Giacchino", movie: "Star Trek", year: 2009 },
    { title: "The Batman Theme", artist: "Michael Giacchino", movie: "The Batman", year: 2022 },
    { title: "The Shape of Water", artist: "Alexandre Desplat", movie: "The Shape of Water", year: 2017 },
    { title: "The Imitation Game", artist: "Alexandre Desplat", movie: "The Imitation Game", year: 2014 },
    { title: "Mr. Moustafa", artist: "Alexandre Desplat", movie: "The Grand Budapest Hotel", year: 2014 },
    { title: "American Beauty", artist: "Thomas Newman", movie: "American Beauty", year: 1999 },
    { title: "Nemo Egg", artist: "Thomas Newman", movie: "Finding Nemo", year: 2003 },
    { title: "Brooks Was Here", artist: "Thomas Newman", movie: "The Shawshank Redemption", year: 1994 },
    { title: "The Night Window", artist: "Thomas Newman", movie: "1917", year: 2019 },
    { title: "Hand Covers Bruise", artist: "Trent Reznor & Atticus Ross", movie: "The Social Network", year: 2010 },
    { title: "On the Nature of Daylight", artist: "Max Richter", movie: "Arrival", year: 2016 },
    { title: "Wakanda", artist: "Ludwig Göransson", movie: "Black Panther", year: 2018 },
    { title: "Can You Hear the Music", artist: "Ludwig Göransson", movie: "Oppenheimer", year: 2023 },
    { title: "Posterity", artist: "Ludwig Göransson", movie: "Tenet", year: 2020 },
    { title: "Bathroom Dance", artist: "Hildur Guðnadóttir", movie: "Joker", year: 2019 },
    { title: "Amélie Waltz", artist: "Yann Tiersen", movie: "Amélie", year: 2001 },
    { title: "Comptine d'un autre été", artist: "Yann Tiersen", movie: "Amélie", year: 2001 },
    { title: "Crouching Tiger, Hidden Dragon", artist: "Tan Dun", movie: "Crouching Tiger, Hidden Dragon", year: 2000 },
    { title: "Test Drive", artist: "John Powell", movie: "How to Train Your Dragon", year: 2010 },
    { title: "Romantic Flight", artist: "John Powell", movie: "How to Train Your Dragon", year: 2010 },
    { title: "Forbidden Friendship", artist: "John Powell", movie: "How to Train Your Dragon", year: 2010 },
    { title: "Lux Aeterna", artist: "Clint Mansell", movie: "Requiem for a Dream", year: 2000 },
    { title: "Promontory", artist: "Trevor Jones", movie: "The Last of the Mohicans", year: 1992 },
    { title: "Misirlou", artist: "Dick Dale", movie: "Pulp Fiction", year: 1994 },
    { title: "Dueling Banjos", artist: "Eric Weissberg", movie: "Deliverance", year: 1972 },
    { title: "The Entertainer", artist: "Marvin Hamlisch", movie: "The Sting", year: 1973 },
    { title: "Cavatina", artist: "John Williams (Guitarist)", movie: "The Deer Hunter", year: 1978 },
    { title: "Theme from Love Story", artist: "Francis Lai", movie: "Love Story", year: 1970 },
    { title: "Arrival to Earth", artist: "Steve Jablonsky", movie: "Transformers", year: 2007 },
    { title: "Truman Sleeps", artist: "Philip Glass", movie: "The Truman Show", year: 1998 },
    { title: "Dawn", artist: "Dario Marianelli", movie: "Pride & Prejudice", year: 2005 },
    { title: "Merry Christmas Mr. Lawrence", artist: "Ryuichi Sakamoto", movie: "Merry Christmas, Mr. Lawrence", year: 1983 },
    { title: "The Last Emperor (Theme)", artist: "Ryuichi Sakamoto", movie: "The Last Emperor", year: 1987 },
    { title: "Battle Without Honor or Humanity", artist: "Tomoyasu Hotei", movie: "Kill Bill: Vol. 1", year: 2003 },
    { title: "Clubbed to Death", artist: "Rob Dougan", movie: "The Matrix", year: 1999 },
    { title: "In the House - In a Heartbeat", artist: "John Murphy", movie: "28 Days Later", year: 2002 },
    { title: "Adagio in D Minor", artist: "John Murphy", movie: "Sunshine", year: 2007 },
    { title: "Pacific Rim", artist: "Ramin Djawadi", movie: "Pacific Rim", year: 2013 }
  ],
  animated_films: [ // Instrumental scores AND songs with vocals allowed.
    // --- Disney Renaissance & Golden Age ---
    { title: "Circle of Life", artist: "Elton John", movie: "The Lion King", year: 1994 },
    { title: "Hakuna Matata", artist: "Nathan Lane", movie: "The Lion King", year: 1994 },
    { title: "Can You Feel the Love Tonight", artist: "Elton John", movie: "The Lion King", year: 1994 },
    { title: "Under the Sea", artist: "Samuel E. Wright", movie: "The Little Mermaid", year: 1989 },
    { title: "Part of Your World", artist: "Jodi Benson", movie: "The Little Mermaid", year: 1989 },
    { title: "Kiss the Girl", artist: "Samuel E. Wright", movie: "The Little Mermaid", year: 1989 },
    { title: "Beauty and the Beast", artist: "Angela Lansbury", movie: "Beauty and the Beast", year: 1991 },
    { title: "Be Our Guest", artist: "Jerry Orbach", movie: "Beauty and the Beast", year: 1991 },
    { title: "Belle", artist: "Paige O'Hara", movie: "Beauty and the Beast", year: 1991 },
    { title: "A Whole New World", artist: "Brad Kane", movie: "Aladdin", year: 1992 },
    { title: "Friend Like Me", artist: "Robin Williams", movie: "Aladdin", year: 1992 },
    { title: "Prince Ali", artist: "Robin Williams", movie: "Aladdin", year: 1992 },
    { title: "Colors of the Wind", artist: "Judy Kuhn", movie: "Pocahontas", year: 1995 },
    { title: "Just Around the Riverbend", artist: "Judy Kuhn", movie: "Pocahontas", year: 1995 },
    { title: "You'll Be in My Heart", artist: "Phil Collins", movie: "Tarzan", year: 1999 },
    { title: "Strangers Like Me", artist: "Phil Collins", movie: "Tarzan", year: 1999 },
    { title: "Son of Man", artist: "Phil Collins", movie: "Tarzan", year: 1999 },
    { title: "Two Worlds", artist: "Phil Collins", movie: "Tarzan", year: 1999 },
    { title: "I'll Make a Man Out of You", artist: "Donny Osmond", movie: "Mulan", year: 1998 },
    { title: "Reflection", artist: "Lea Salonga", movie: "Mulan", year: 1998 },
    { title: "Honor to Us All", artist: "Lea Salonga", movie: "Mulan", year: 1998 },
    { title: "Go the Distance", artist: "Roger Bart", movie: "Hercules", year: 1997 },
    { title: "Zero to Hero", artist: "Lillias White", movie: "Hercules", year: 1997 },
    { title: "I Won't Say (I'm in Love)", artist: "Susan Egan", movie: "Hercules", year: 1997 },
    { title: "God Help the Outcasts", artist: "Heidi Mollenhauer", movie: "The Hunchback of Notre Dame", year: 1996 },
    { title: "Out There", artist: "Tony Jay", movie: "The Hunchback of Notre Dame", year: 1996 },
    { title: "The Bare Necessities", artist: "Phil Harris", movie: "The Jungle Book", year: 1967 },
    { title: "I Wan'na Be Like You", artist: "Louis Prima", movie: "The Jungle Book", year: 1967 },
    { title: "Bibbidi-Bobbidi-Boo", artist: "Verna Felton", movie: "Cinderella", year: 1950 },
    { title: "A Dream Is a Wish Your Heart Makes", artist: "Ilene Woods", movie: "Cinderella", year: 1950 },
    { title: "When You Wish Upon a Star", artist: "Cliff Edwards", movie: "Pinocchio", year: 1940 },
    { title: "Whistle While You Work", artist: "Adriana Caselotti", movie: "Snow White and the Seven Dwarfs", year: 1937 },
    { title: "Heigh-Ho", artist: "The Dwarfs", movie: "Snow White and the Seven Dwarfs", year: 1937 },
    { title: "Once Upon a Dream", artist: "Mary Costa", movie: "Sleeping Beauty", year: 1959 },
    { title: "Cruella De Vil", artist: "Bill Lee", movie: "One Hundred and One Dalmatians", year: 1961 },
    { title: "Bella Notte", artist: "George Givot", movie: "Lady and the Tramp", year: 1955 },
    { title: "You Can Fly! You Can Fly!", artist: "Bobby Driscoll", movie: "Peter Pan", year: 1953 },
    { title: "Everybody Wants to Be a Cat", artist: "Scatman Crothers", movie: "The Aristocats", year: 1970 },
    { title: "Hawaiian Roller Coaster Ride", artist: "Mark Keali'i Ho'omalu", movie: "Lilo & Stitch", year: 2002 },
    { title: "He Mele No Lilo", artist: "Mark Keali'i Ho'omalu", movie: "Lilo & Stitch", year: 2002 },
    { title: "I'm Still Here", artist: "John Rzeznik", movie: "Treasure Planet", year: 2002 },
    { title: "On My Way", artist: "Phil Collins", movie: "Brother Bear", year: 2003 },
    { title: "My Funny Friend and Me", artist: "Sting", movie: "The Emperor's New Groove", year: 2000 },
    { title: "Why Should I Worry?", artist: "Billy Joel", movie: "Oliver & Company", year: 1988 },
    { title: "I2I", artist: "Tevin Campbell", movie: "A Goofy Movie", year: 1995 },
    { title: "Stand Out", artist: "Tevin Campbell", movie: "A Goofy Movie", year: 1995 },
    { title: "Oo-De-Lally", artist: "Roger Miller", movie: "Robin Hood", year: 1973 },
    
    // --- Pixar ---
    { title: "You've Got a Friend in Me", artist: "Randy Newman", movie: "Toy Story", year: 1995 },
    { title: "I Will Go Sailing No More", artist: "Randy Newman", movie: "Toy Story", year: 1995 },
    { title: "Strange Things", artist: "Randy Newman", movie: "Toy Story", year: 1995 },
    { title: "When She Loved Me", artist: "Sarah McLachlan", movie: "Toy Story 2", year: 1999 },
    { title: "Woody's Roundup", artist: "Riders in the Sky", movie: "Toy Story 2", year: 1999 },
    { title: "We Belong Together", artist: "Randy Newman", movie: "Toy Story 3", year: 2010 },
    { title: "Married Life", artist: "Michael Giacchino", movie: "Up", year: 2009 },
    { title: "The Incredibles Suite", artist: "Michael Giacchino", movie: "The Incredibles", year: 2004 },
    { title: "Life's Incredible Again", artist: "Michael Giacchino", movie: "The Incredibles", year: 2004 },
    { title: "If I Didn't Have You", artist: "Billy Crystal", movie: "Monsters, Inc.", year: 2001 },
    { title: "The Scare Floor", artist: "Randy Newman", movie: "Monsters, Inc.", year: 2001 },
    { title: "Remember Me", artist: "Benjamin Bratt", movie: "Coco", year: 2017 },
    { title: "Un Poco Loco", artist: "Anthony Gonzalez", movie: "Coco", year: 2017 },
    { title: "Proud Corazón", artist: "Anthony Gonzalez", movie: "Coco", year: 2017 },
    { title: "Le Festin", artist: "Camille", movie: "Ratatouille", year: 2007 },
    { title: "Nemo Egg", artist: "Thomas Newman", movie: "Finding Nemo", year: 2003 },
    { title: "Beyond the Sea", artist: "Robbie Williams", movie: "Finding Nemo", year: 2003 },
    { title: "Life is a Highway", artist: "Rascal Flatts", movie: "Cars", year: 2006 },
    { title: "Real Gone", artist: "Sheryl Crow", movie: "Cars", year: 2006 },
    { title: "Our Town", artist: "James Taylor", movie: "Cars", year: 2006 },
    { title: "Touch the Sky", artist: "Julie Fowlis", movie: "Brave", year: 2012 },
    { title: "Nobody Like U", artist: "4*TOWN", movie: "Turning Red", year: 2022 },
    { title: "Steal the Show", artist: "Lauv", movie: "Elemental", year: 2023 },
    { title: "Down to Earth", artist: "Peter Gabriel", movie: "WALL-E", year: 2008 },
    { title: "Bundle of Joy", artist: "Michael Giacchino", movie: "Inside Out", year: 2015 },
    { title: "It's All Right", artist: "Jon Batiste", movie: "Soul", year: 2020 },

    // --- Modern Disney (Frozen/Moana/Encanto) ---
    { title: "Let It Go", artist: "Idina Menzel", movie: "Frozen", year: 2013 },
    { title: "Do You Want to Build a Snowman?", artist: "Kristen Bell", movie: "Frozen", year: 2013 },
    { title: "For the First Time in Forever", artist: "Kristen Bell", movie: "Frozen", year: 2013 },
    { title: "Love Is an Open Door", artist: "Kristen Bell", movie: "Frozen", year: 2013 },
    { title: "Into the Unknown", artist: "Idina Menzel", movie: "Frozen II", year: 2019 },
    { title: "Show Yourself", artist: "Idina Menzel", movie: "Frozen II", year: 2019 },
    { title: "How Far I'll Go", artist: "Auli'i Cravalho", movie: "Moana", year: 2016 },
    { title: "You're Welcome", artist: "Dwayne Johnson", movie: "Moana", year: 2016 },
    { title: "Shiny", artist: "Jemaine Clement", movie: "Moana", year: 2016 },
    { title: "We Don't Talk About Bruno", artist: "Encanto Cast", movie: "Encanto", year: 2021 },
    { title: "Surface Pressure", artist: "Jessica Darrow", movie: "Encanto", year: 2021 },
    { title: "Dos Oruguitas", artist: "Sebastián Yatra", movie: "Encanto", year: 2021 },
    { title: "The Family Madrigal", artist: "Stephanie Beatriz", movie: "Encanto", year: 2021 },
    { title: "I See the Light", artist: "Mandy Moore", movie: "Tangled", year: 2010 },
    { title: "When Will My Life Begin?", artist: "Mandy Moore", movie: "Tangled", year: 2010 },
    { title: "Almost There", artist: "Anika Noni Rose", movie: "The Princess and the Frog", year: 2009 },
    { title: "Friends on the Other Side", artist: "Keith David", movie: "The Princess and the Frog", year: 2009 },
    { title: "Dig a Little Deeper", artist: "Jenifer Lewis", movie: "The Princess and the Frog", year: 2009 },
    { title: "Down in New Orleans", artist: "Dr. John", movie: "The Princess and the Frog", year: 2009 },
    { title: "Try Everything", artist: "Shakira", movie: "Zootopia", year: 2016 },
    { title: "Immortals", artist: "Fall Out Boy", movie: "Big Hero 6", year: 2014 },
    { title: "When Can I See You Again?", artist: "Owl City", movie: "Wreck-It Ralph", year: 2012 },
    { title: "This Wish", artist: "Ariana DeBose", movie: "Wish", year: 2023 },

    // --- Dreamworks & Others ---
    { title: "All Star", artist: "Smash Mouth", movie: "Shrek", year: 2001 },
    { title: "I'm a Believer", artist: "Smash Mouth", movie: "Shrek", year: 2001 },
    { title: "Hallelujah", artist: "Rufus Wainwright", movie: "Shrek", year: 2001 },
    { title: "Accidentally in Love", artist: "Counting Crows", movie: "Shrek 2", year: 2004 },
    { title: "Holding Out for a Hero", artist: "Jennifer Saunders", movie: "Shrek 2", year: 2004 },
    { title: "Fairytale", artist: "Harry Gregson-Williams", movie: "Shrek", year: 2001 },
    { title: "Test Drive", artist: "John Powell", movie: "How to Train Your Dragon", year: 2010 },
    { title: "Kung Fu Fighting", artist: "CeeLo Green", movie: "Kung Fu Panda", year: 2008 },
    { title: "Oogway Ascends", artist: "Hans Zimmer", movie: "Kung Fu Panda", year: 2008 },
    { title: "Sunflower", artist: "Post Malone", movie: "Spider-Man: Into the Spider-Verse", year: 2018 },
    { title: "What's Up Danger", artist: "Blackway", movie: "Spider-Man: Into the Spider-Verse", year: 2018 },
    { title: "Everything Is Awesome", artist: "Tegan and Sara", movie: "The Lego Movie", year: 2014 },
    { title: "This Is Halloween", artist: "Danny Elfman", movie: "The Nightmare Before Christmas", year: 1993 },
    { title: "What's This?", artist: "Danny Elfman", movie: "The Nightmare Before Christmas", year: 1993 },
    { title: "Path of the Wind", artist: "Joe Hisaishi", movie: "My Neighbor Totoro", year: 1988 },
    { title: "Merry-Go-Round of Life", artist: "Joe Hisaishi", movie: "Howl's Moving Castle", year: 2004 },
    { title: "One Summer's Day", artist: "Joe Hisaishi", movie: "Spirited Away", year: 2001 },
    { title: "When You Believe", artist: "Mariah Carey", movie: "The Prince of Egypt", year: 1998 },
    { title: "Journey to the Past", artist: "Liz Callaway", movie: "Anastasia", year: 1997 },
    { title: "Once Upon a December", artist: "Liz Callaway", movie: "Anastasia", year: 1997 },
    { title: "Somewhere Out There", artist: "Linda Ronstadt", movie: "An American Tail", year: 1986 },
    { title: "Peaches", artist: "Jack Black", movie: "The Super Mario Bros. Movie", year: 2023 }
  ],
  modern_tv: [ // Intro themes only. Shows airing 2000 onwards.
    // --- Prestige Drama ---
    { title: "Game of Thrones Main Title", artist: "Ramin Djawadi", movie: "Game of Thrones", year: 2011 },
    { title: "Succession (Main Title)", artist: "Nicholas Britell", movie: "Succession", year: 2018 },
    { title: "The White Lotus Theme", artist: "Cristobal Tapia de Veer", movie: "The White Lotus", year: 2021 },
    { title: "Breaking Bad Theme", artist: "Dave Porter", movie: "Breaking Bad", year: 2008 },
    { title: "Better Call Saul Theme", artist: "Little Barrie", movie: "Better Call Saul", year: 2015 },
    { title: "A Beautiful Mine", artist: "RJD2", movie: "Mad Men", year: 2007 },
    { title: "Woke Up This Morning", artist: "Alabama 3", movie: "The Sopranos", year: 1999 }, // Ran mostly in 2000s
    { title: "Way Down in the Hole", artist: "The Blind Boys of Alabama", movie: "The Wire", year: 2002 },
    { title: "Dexter Main Title", artist: "Rolfe Kent", movie: "Dexter", year: 2006 },
    { title: "Lost Main Title", artist: "Michael Giacchino", movie: "Lost", year: 2004 },
    { title: "Downton Abbey Theme", artist: "John Lunn", movie: "Downton Abbey", year: 2010 },
    { title: "The Crown Main Title", artist: "Hans Zimmer", movie: "The Crown", year: 2016 },
    { title: "Westworld Main Title", artist: "Ramin Djawadi", movie: "Westworld", year: 2016 },
    { title: "House of Cards Theme", artist: "Jeff Beal", movie: "House of Cards", year: 2013 },
    { title: "Homeland Theme", artist: "Sean Callery", movie: "Homeland", year: 2011 },
    { title: "This Is Us Theme", artist: "Siddhartha Khosla", movie: "This Is Us", year: 2016 },
    { title: "Yellowstone Theme", artist: "Brian Tyler", movie: "Yellowstone", year: 2018 },
    { title: "Severance Main Title", artist: "Theodore Shapiro", movie: "Severance", year: 2022 },
    { title: "The Handmaid's Tale Theme", artist: "Adam Taylor", movie: "The Handmaid's Tale", year: 2017 },
    { title: "Big Little Lies Theme", artist: "Michael Kiwanuka", movie: "Big Little Lies", year: 2017 },
    { title: "True Detective Theme", artist: "The Handsome Family", movie: "True Detective", year: 2014 },
    { title: "Fargo Theme", artist: "Jeff Russo", movie: "Fargo", year: 2014 },
    { title: "Peaky Blinders Theme", artist: "Nick Cave", movie: "Peaky Blinders", year: 2013 },
    { title: "Mr. Robot Theme", artist: "Mac Quayle", movie: "Mr. Robot", year: 2015 },
    { title: "Tuyo (Narcos Theme)", artist: "Rodrigo Amarante", movie: "Narcos", year: 2015 },
    { title: "Squid Game Theme", artist: "Jung Jae-il", movie: "Squid Game", year: 2021 },
    { title: "The Last of Us Theme", artist: "Gustavo Santaolalla", movie: "The Last of Us", year: 2023 },
    { title: "House of the Dragon Theme", artist: "Ramin Djawadi", movie: "House of the Dragon", year: 2022 },
    { title: "Succession Theme", artist: "Nicholas Britell", movie: "Succession", year: 2018 },
    { title: "Ozark Theme", artist: "Danny Bensi", movie: "Ozark", year: 2017 },
    { title: "Mindhunter Theme", artist: "Jason Hill", movie: "Mindhunter", year: 2017 },

    // --- Comedy/Sitcom ---
    { title: "The Office Theme", artist: "The Scrantones", movie: "The Office (US)", year: 2005 },
    { title: "Parks and Recreation Theme", artist: "Gaby Moreno", movie: "Parks and Recreation", year: 2009 },
    { title: "30 Rock Theme", artist: "Jeff Richmond", movie: "30 Rock", year: 2006 },
    { title: "At Least It Was Here", artist: "The 88", movie: "Community", year: 2009 },
    { title: "Arrested Development Theme", artist: "David Schwartz", movie: "Arrested Development", year: 2003 },
    { title: "Modern Family Theme", artist: "Gabriel Mann", movie: "Modern Family", year: 2009 },
    { title: "Hey Beautiful", artist: "The Solids", movie: "How I Met Your Mother", year: 2005 },
    { title: "The History of Everything", artist: "Barenaked Ladies", movie: "The Big Bang Theory", year: 2007 },
    { title: "Brooklyn Nine-Nine", artist: "Dan Marocco", movie: "Brooklyn Nine-Nine", year: 2013 },
    { title: "Ted Lasso Theme", artist: "Marcus Mumford", movie: "Ted Lasso", year: 2020 },
    { title: "Where You Lead", artist: "Carole King", movie: "Gilmore Girls", year: 2000 },
    { title: "Superman", artist: "Lazlo Bane", movie: "Scrubs", year: 2001 },
    { title: "Frolic (Curb Theme)", artist: "Luciano Michelini", movie: "Curb Your Enthusiasm", year: 2000 },
    { title: "Boss of Me", artist: "They Might Be Giants", movie: "Malcolm in the Middle", year: 2000 },
    { title: "Hey Girl", artist: "Zooey Deschanel", movie: "New Girl", year: 2011 },
    { title: "It's a Jungle Out There", artist: "Randy Newman", movie: "Monk", year: 2002 },
    { title: "I Know You Know", artist: "The Friendly Indians", movie: "Psych", year: 2006 },
    { title: "Entourage Theme", artist: "Jane's Addiction", movie: "Entourage", year: 2004 },
    { title: "Veep Theme", artist: "Rupert Gregson-Williams", movie: "Veep", year: 2012 },
    { title: "Only Murders in the Building", artist: "Siddhartha Khosla", movie: "Only Murders in the Building", year: 2021 },
    { title: "The Bear Theme", artist: "Refused", movie: "The Bear", year: 2022 },
    { title: "Schitt's Creek Theme", artist: "Maribeth Solomon", movie: "Schitt's Creek", year: 2015 },
    { title: "Unbreakable Kimmy Schmidt", artist: "The Gregory Brothers", movie: "Unbreakable Kimmy Schmidt", year: 2015 },
    { title: "BoJack Horseman Theme", artist: "Patrick Carney", movie: "BoJack Horseman", year: 2014 },
    { title: "Rick and Morty Theme", artist: "Ryan Elder", movie: "Rick and Morty", year: 2013 },
    { title: "Bob's Burgers Theme", artist: "Loren Bouchard", movie: "Bob's Burgers", year: 2011 },
    { title: "Archer Theme", artist: "Scott Sims", movie: "Archer", year: 2009 },
    { title: "Adventure Time", artist: "Pendleton Ward", movie: "Adventure Time", year: 2010 },

    // --- Action/Sci-Fi/Fantasy ---
    { title: "Stranger Things Theme", artist: "Kyle Dixon", movie: "Stranger Things", year: 2016 },
    { title: "The Mandalorian", artist: "Ludwig Goransson", movie: "The Mandalorian", year: 2019 },
    { title: "The Witcher Theme", artist: "Sonya Belousova", movie: "The Witcher", year: 2019 },
    { title: "Toss A Coin To Your Witcher", artist: "Sonya Belousova", movie: "The Witcher", year: 2019 },
    { title: "Agatha All Along", artist: "Kristen Anderson-Lopez", movie: "WandaVision", year: 2021 },
    { title: "WandaVision Theme", artist: "Kristen Anderson-Lopez", movie: "WandaVision", year: 2021 },
    { title: "Loki Theme", artist: "Natalie Holt", movie: "Loki", year: 2021 },
    { title: "Daredevil Theme", artist: "John Paesano", movie: "Daredevil", year: 2015 },
    { title: "The Boys Theme", artist: "Christopher Lennertz", movie: "The Boys", year: 2019 },
    { title: "Wednesday Main Titles", artist: "Danny Elfman", movie: "Wednesday", year: 2022 },
    { title: "Sherlock Theme", artist: "David Arnold", movie: "Sherlock", year: 2010 },
    { title: "Doctor Who Theme", artist: "Murray Gold", movie: "Doctor Who", year: 2005 },
    { title: "Ballad of Serenity", artist: "Sonny Rhodes", movie: "Firefly", year: 2002 },
    { title: "Battlestar Galactica Theme", artist: "Bear McCreary", movie: "Battlestar Galactica", year: 2004 },
    { title: "Orphan Black Theme", artist: "Two Fingers", movie: "Orphan Black", year: 2013 },
    { title: "Black Mirror Theme", artist: "Stuart Earl", movie: "Black Mirror", year: 2011 },
    { title: "Outlander Theme", artist: "Bear McCreary", movie: "Outlander", year: 2014 },
    { title: "Arcane Theme", artist: "Imagine Dragons", movie: "Arcane", year: 2021 },

    // --- Drama/Soaps/Teens ---
    { title: "Cosy in the Rocket", artist: "Psapp", movie: "Grey's Anatomy", year: 2005 },
    { title: "Teardrop", artist: "Massive Attack", movie: "House", year: 2004 },
    { title: "Desperate Housewives Theme", artist: "Danny Elfman", movie: "Desperate Housewives", year: 2004 },
    { title: "Bad Things", artist: "Jace Everett", movie: "True Blood", year: 2008 },
    { title: "We Used to Be Friends", artist: "The Dandy Warhols", movie: "Veronica Mars", year: 2004 },
    { title: "Secret", artist: "The Pierces", movie: "Pretty Little Liars", year: 2010 },
    { title: "California", artist: "Phantom Planet", movie: "The O.C.", year: 2003 },
    { title: "I Don't Want to Be", artist: "Gavin DeGraw", movie: "One Tree Hill", year: 2003 },
    { title: "Save Me", artist: "Remy Zero", movie: "Smallville", year: 2001 },
    { title: "Unwritten", artist: "Natasha Bedingfield", movie: "The Hills", year: 2006 },
    { title: "Scandal Theme", artist: "Chad Fischer", movie: "Scandal", year: 2012 },
    { title: "Bridgerton Theme", artist: "Kris Bowers", movie: "Bridgerton", year: 2020 },
    { title: "Euphoria Theme", artist: "Labrinth", movie: "Euphoria", year: 2019 },
    { title: "Orange Is the New Black Theme", artist: "Regina Spektor", movie: "Orange Is the New Black", year: 2013 },
    { title: "Shameless Theme", artist: "The High Strung", movie: "Shameless", year: 2011 },
    { title: "Sons of Anarchy Theme", artist: "Curtis Stigers", movie: "Sons of Anarchy", year: 2008 },
    { title: "Long Hard Times to Come", artist: "Gangstagrass", movie: "Justified", year: 2010 },
    { title: "Glee Theme", artist: "Glee Cast", movie: "Glee", year: 2009 },
    { title: "Empire Theme", artist: "Filthy Rich", movie: "Empire", year: 2015 },
    { title: "Friday Night Lights Theme", artist: "Explosions in the Sky", movie: "Friday Night Lights", year: 2006 }
  ],
  classic_tv: [ // Intro themes only. Shows airing BEFORE 2000.
    // --- Sitcoms ---
    { title: "I'll Be There for You", artist: "The Rembrandts", movie: "Friends", year: 1994 },
    { title: "Seinfeld Theme", artist: "Jonathan Wolff", movie: "Seinfeld", year: 1989 },
    { title: "Tossed Salads and Scrambled Eggs", artist: "Kelsey Grammer", movie: "Frasier", year: 1993 },
    { title: "Where Everybody Knows Your Name", artist: "Gary Portnoy", movie: "Cheers", year: 1982 },
    { title: "Thank You for Being a Friend", artist: "Cynthia Fee", movie: "The Golden Girls", year: 1985 },
    { title: "Everywhere You Look", artist: "Jesse Frederick", movie: "Full House", year: 1987 },
    { title: "As Days Go By", artist: "Jesse Frederick", movie: "Family Matters", year: 1989 },
    { title: "Saved by the Bell", artist: "Michael Damian", movie: "Saved by the Bell", year: 1989 },
    { title: "The Fresh Prince of Bel-Air", artist: "Will Smith", movie: "The Fresh Prince of Bel-Air", year: 1990 },
    { title: "Love and Marriage", artist: "Frank Sinatra", movie: "Married... with Children", year: 1987 },
    { title: "The Simpsons Theme", artist: "Danny Elfman", movie: "The Simpsons", year: 1989 },
    { title: "Angela", artist: "Bob James", movie: "Taxi", year: 1978 },
    { title: "Happy Days", artist: "Pratt & McClain", movie: "Happy Days", year: 1974 },
    { title: "Making Our Dreams Come True", artist: "Cyndi Grecco", movie: "Laverne & Shirley", year: 1976 },
    { title: "Come and Knock on Our Door", artist: "Ray Charles", movie: "Three's Company", year: 1977 },
    { title: "It Takes Diff'rent Strokes", artist: "Alan Thicke", movie: "Diff'rent Strokes", year: 1978 },
    { title: "Movin' On Up", artist: "Ja'net Dubois", movie: "The Jeffersons", year: 1975 },
    { title: "Good Times", artist: "Jim Gilstrap", movie: "Good Times", year: 1974 },
    { title: "The Streetbeater", artist: "Quincy Jones", movie: "Sanford and Son", year: 1972 },
    { title: "Those Were the Days", artist: "Carroll O'Connor", movie: "All in the Family", year: 1971 },
    { title: "Love is All Around", artist: "Sonny Curtis", movie: "The Mary Tyler Moore Show", year: 1970 },
    { title: "The Brady Bunch", artist: "Peppermint Trolley Company", movie: "The Brady Bunch", year: 1969 },
    { title: "The Ballad of Gilligan's Isle", artist: "The Wellingtons", movie: "Gilligan's Island", year: 1964 },
    { title: "I Dream of Jeannie", artist: "Hugo Montenegro", movie: "I Dream of Jeannie", year: 1965 },
    { title: "Bewitched", artist: "Howard Greenfield", movie: "Bewitched", year: 1964 },
    { title: "The Addams Family", artist: "Vic Mizzy", movie: "The Addams Family", year: 1964 },
    { title: "The Munsters", artist: "Jack Marshall", movie: "The Munsters", year: 1964 },
    { title: "Meet the Flintstones", artist: "Hoyt Curtin", movie: "The Flintstones", year: 1960 },
    { title: "The Jetsons", artist: "Hoyt Curtin", movie: "The Jetsons", year: 1962 },
    { title: "Get Smart Theme", artist: "Irving Szathmary", movie: "Get Smart", year: 1965 },
    { title: "Monkees Theme", artist: "The Monkees", movie: "The Monkees", year: 1966 },
    { title: "Scooby-Doo, Where Are You!", artist: "Larry Marks", movie: "Scooby-Doo", year: 1969 },
    { title: "Come On Get Happy", artist: "The Partridge Family", movie: "The Partridge Family", year: 1970 },
    { title: "MASH Theme", artist: "Johnny Mandel", movie: "M*A*S*H", year: 1972 },
    { title: "The Fishin' Hole", artist: "Earle Hagen", movie: "The Andy Griffith Show", year: 1960 },
    { title: "The Dick Van Dyke Show", artist: "Earle Hagen", movie: "The Dick Van Dyke Show", year: 1961 },
    { title: "Green Acres", artist: "Vic Mizzy", movie: "Green Acres", year: 1965 },
    { title: "The Ballad of Jed Clampett", artist: "Jerry Scoggins", movie: "The Beverly Hillbillies", year: 1962 },
    { title: "Home Improvement Theme", artist: "Dan Foliart", movie: "Home Improvement", year: 1991 },
    { title: "Roseanne Theme", artist: "Dan Foliart", movie: "Roseanne", year: 1988 },
    { title: "As Long As We Got Each Other", artist: "B.J. Thomas", movie: "Growing Pains", year: 1985 },
    { title: "Without Us", artist: "Johnny Mathis", movie: "Family Ties", year: 1982 },
    { title: "Facts of Life", artist: "Gloria Loring", movie: "The Facts of Life", year: 1979 },
    { title: "Diff'rent Strokes", artist: "Alan Thicke", movie: "Diff'rent Strokes", year: 1978 },
    { title: "Perfect Strangers Theme", artist: "David Pomeranz", movie: "Perfect Strangers", year: 1986 },
    { title: "Brand New Life", artist: "Steve Wariner", movie: "Who's the Boss?", year: 1984 },
    { title: "Designing Women Theme", artist: "Doc Severinsen", movie: "Designing Women", year: 1986 },
    { title: "Murphy Brown Theme", artist: "Steve Dorff", movie: "Murphy Brown", year: 1988 },
    { title: "The Nanny Named Fran", artist: "Ann Hampton Callaway", movie: "The Nanny", year: 1993 },
    { title: "Everybody Loves Raymond", artist: "Rick Marotta", movie: "Everybody Loves Raymond", year: 1996 },
    { title: "King of the Hill Theme", artist: "The Refreshments", movie: "King of the Hill", year: 1997 },
    { title: "South Park Theme", artist: "Primus", movie: "South Park", year: 1997 },
    { title: "Family Guy Theme", artist: "Walter Murphy", movie: "Family Guy", year: 1999 },
    { title: "Futurama Theme", artist: "Christopher Tyng", movie: "Futurama", year: 1999 },
    { title: "SpongeBob SquarePants Theme", artist: "Patrick Pinney", movie: "SpongeBob SquarePants", year: 1999 },
    { title: "That '70s Show Theme", artist: "Cheap Trick", movie: "That '70s Show", year: 1998 },
    { title: "Freaks and Geeks Theme", artist: "Joan Jett", movie: "Freaks and Geeks", year: 1999 },

    // --- Action/Drama/Sci-Fi ---
    { title: "The X-Files", artist: "Mark Snow", movie: "The X-Files", year: 1993 },
    { title: "Twin Peaks Theme", artist: "Angelo Badalamenti", movie: "Twin Peaks", year: 1990 },
    { title: "Law & Order", artist: "Mike Post", movie: "Law & Order", year: 1990 },
    { title: "Batman Theme", artist: "Neal Hefti", movie: "Batman", year: 1966 },
    { title: "Mission: Impossible", artist: "Lalo Schifrin", movie: "Mission: Impossible", year: 1966 },
    { title: "Hawaii Five-O", artist: "The Ventures", movie: "Hawaii Five-O", year: 1968 },
    { title: "Theme from Magnum P.I.", artist: "Mike Post", movie: "Magnum, P.I.", year: 1980 },
    { title: "Miami Vice Theme", artist: "Jan Hammer", movie: "Miami Vice", year: 1984 },
    { title: "Knight Rider Theme", artist: "Stu Phillips", movie: "Knight Rider", year: 1982 },
    { title: "The A-Team Theme", artist: "Mike Post", movie: "The A-Team", year: 1983 },
    { title: "MacGyver Theme", artist: "Randy Edelman", movie: "MacGyver", year: 1985 },
    { title: "Good Ol' Boys", artist: "Waylon Jennings", movie: "The Dukes of Hazzard", year: 1979 },
    { title: "With a Little Help From My Friends", artist: "Joe Cocker", movie: "The Wonder Years", year: 1988 },
    { title: "I'm Always Here", artist: "Jimi Jamison", movie: "Baywatch", year: 1989 },
    { title: "Bad Boys", artist: "Inner Circle", movie: "Cops", year: 1989 },
    { title: "Star Trek Theme", artist: "Alexander Courage", movie: "Star Trek", year: 1966 },
    { title: "Star Trek: TNG Theme", artist: "Jerry Goldsmith", movie: "Star Trek: The Next Generation", year: 1987 },
    { title: "Star Trek: DS9 Theme", artist: "Dennis McCarthy", movie: "Star Trek: Deep Space Nine", year: 1993 },
    { title: "Star Trek: Voyager Theme", artist: "Jerry Goldsmith", movie: "Star Trek: Voyager", year: 1995 },
    { title: "The Twilight Zone", artist: "Marius Constant", movie: "The Twilight Zone", year: 1959 },
    { title: "Alfred Hitchcock Presents", artist: "Charles Gounod", movie: "Alfred Hitchcock Presents", year: 1955 },
    { title: "Perry Mason Theme", artist: "Fred Steiner", movie: "Perry Mason", year: 1957 },
    { title: "Bonanza Theme", artist: "Jay Livingston", movie: "Bonanza", year: 1959 },
    { title: "Rawhide", artist: "Frankie Laine", movie: "Rawhide", year: 1959 },
    { title: "Dallas Theme", artist: "Jerrold Immel", movie: "Dallas", year: 1978 },
    { title: "Dynasty Theme", artist: "Bill Conti", movie: "Dynasty", year: 1981 },
    { title: "Hill Street Blues Theme", artist: "Mike Post", movie: "Hill Street Blues", year: 1981 },
    { title: "St. Elsewhere Theme", artist: "Dave Grusin", movie: "St. Elsewhere", year: 1982 },
    { title: "L.A. Law Theme", artist: "Mike Post", movie: "L.A. Law", year: 1986 },
    { title: "NYPD Blue Theme", artist: "Mike Post", movie: "NYPD Blue", year: 1993 },
    { title: "ER Theme", artist: "James Newton Howard", movie: "ER", year: 1994 },
    { title: "The West Wing Theme", artist: "W.G. Snuffy Walden", movie: "The West Wing", year: 1999 },
    { title: "Buffy the Vampire Slayer Theme", artist: "Nerf Herder", movie: "Buffy the Vampire Slayer", year: 1997 },
    { title: "How Soon Is Now?", artist: "Love Spit Love", movie: "Charmed", year: 1998 },
    { title: "Dawson's Creek Theme", artist: "Paula Cole", movie: "Dawson's Creek", year: 1998 },
    { title: "I Don't Want to Wait", artist: "Paula Cole", movie: "Dawson's Creek", year: 1998 },
    { title: "Searchin' My Soul", artist: "Vonda Shepard", movie: "Ally McBeal", year: 1997 },
    { title: "Closer to Free", artist: "BoDeans", movie: "Party of Five", year: 1994 },
    { title: "Beverly Hills 90210", artist: "John E. Davis", movie: "Beverly Hills, 90210", year: 1990 },
    { title: "Melrose Place Theme", artist: "Tim Truman", movie: "Melrose Place", year: 1992 },
    { title: "Believe It or Not", artist: "Joey Scarbury", movie: "The Greatest American Hero", year: 1981 },
    { title: "Moonlighting", artist: "Al Jarreau", movie: "Moonlighting", year: 1985 },
    { title: "Airwolf Theme", artist: "Sylvester Levay", movie: "Airwolf", year: 1984 },
    { title: "Peter Gunn", artist: "Henry Mancini", movie: "Peter Gunn", year: 1958 },
    { title: "Dragnet Theme", artist: "Walter Schumann", movie: "Dragnet", year: 1951 },
    { title: "The Love Boat", artist: "Jack Jones", movie: "The Love Boat", year: 1977 },
    { title: "Fantasy Island", artist: "Laurence Rosenthal", movie: "Fantasy Island", year: 1977 },
    { title: "Charlie's Angels Theme", artist: "Jack Elliott", movie: "Charlie's Angels", year: 1976 },
    { title: "Wonder Woman", artist: "Charles Fox", movie: "Wonder Woman", year: 1975 },
    { title: "The Incredible Hulk", artist: "Joe Harnell", movie: "The Incredible Hulk", year: 1978 },
    { title: "Murder, She Wrote", artist: "John Addison", movie: "Murder, She Wrote", year: 1984 },
    { title: "Matlock Theme", artist: "Dick DeBenedictis", movie: "Matlock", year: 1986 },
    { title: "Walker, Texas Ranger", artist: "Chuck Norris", movie: "Walker, Texas Ranger", year: 1993 },
    { title: "Unsolved Mysteries", artist: "Gary Malkin", movie: "Unsolved Mysteries", year: 1987 },
    { title: "Reading Rainbow", artist: "Tina Fabrique", movie: "Reading Rainbow", year: 1983 },
    { title: "Mister Rogers' Neighborhood", artist: "Fred Rogers", movie: "Mister Rogers' Neighborhood", year: 1968 },
    { title: "Sesame Street Theme", artist: "The Kids", movie: "Sesame Street", year: 1969 },
    { title: "The Muppet Show Theme", artist: "The Muppets", movie: "The Muppet Show", year: 1976 },
    { title: "Fraggle Rock Theme", artist: "The Fraggles", movie: "Fraggle Rock", year: 1983 },
    { title: "DuckTales Theme", artist: "Jeff Pescetto", movie: "DuckTales", year: 1987 },
    { title: "Teenage Mutant Ninja Turtles", artist: "Chuck Lorre", movie: "Teenage Mutant Ninja Turtles", year: 1987 },
    { title: "Pokémon Theme", artist: "Jason Paige", movie: "Pokémon", year: 1998 },
    { title: "Go Go Power Rangers", artist: "Ron Wasserman", movie: "Mighty Morphin Power Rangers", year: 1993 },
    { title: "X-Men: The Animated Series", artist: "Ron Wasserman", movie: "X-Men", year: 1992 },
    { title: "Batman: The Animated Series", artist: "Danny Elfman", movie: "Batman: The Animated Series", year: 1992 },
    { title: "Inspector Gadget", artist: "Shuki Levy", movie: "Inspector Gadget", year: 1983 },
    { title: "ThunderCats", artist: "Bernard Hoffer", movie: "ThunderCats", year: 1985 },
    { title: "Transformers", artist: "Anne Bryant", movie: "The Transformers", year: 1984 },
    { title: "G.I. Joe", artist: "Ford Kinder", movie: "G.I. Joe: A Real American Hero", year: 1983 },
    { title: "Captain Planet", artist: "Tom Worrall", movie: "Captain Planet", year: 1990 },
    { title: "Animaniacs", artist: "Rob Paulsen", movie: "Animaniacs", year: 1993 }
  ]
};