// --- TRIVIA DATASETS ---
export const CATEGORIES = {
  testing_category: [
    { title: "007 Theme", artist: "Monty Norman", movie: "Dr. No", year: 1962, hint: "First James Bond film released." },
    { title: "Dexter's Laboratory Theme", artist: "Thomas Chase", movie: "Dexter's Laboratory", year: 1996, hint: "Boy genius hides lab from sister." }
  ],
  all_time_scores: [ // Instrumental scores only. No lyrical songs. Max 3 per film.
    // --- John Williams ---
    { title: "The Imperial March", artist: "John Williams", movie: "The Empire Strikes Back", year: 1980, hint: "Luke trains with Yoda on Dagobah." },
    { title: "Main Title", artist: "John Williams", movie: "Star Wars: A New Hope", year: 1977, hint: "Farm boy joins rebellion against Empire." },
    { title: "Duel of the Fates", artist: "John Williams", movie: "Star Wars: The Phantom Menace", year: 1999, hint: "Anakin wins the Boonta Eve race." },
    { title: "Hedwig's Theme", artist: "John Williams", movie: "Harry Potter and the Sorcerer's Stone", year: 2001, hint: "Boy discovers he is a wizard." },
    { title: "Harry's Wondrous World", artist: "John Williams", movie: "Harry Potter and the Sorcerer's Stone", year: 2001, hint: "Three friends protect the Sorcerer's Stone." },
    { title: "Theme from Jurassic Park", artist: "John Williams", movie: "Jurassic Park", year: 1993, hint: "Cloned dinosaurs escape on island." },
    { title: "Journey to the Island", artist: "John Williams", movie: "Jurassic Park", year: 1993, hint: "Chaos theory mathematician visits park." },
    { title: "Theme from Schindler's List", artist: "John Williams", movie: "Schindler's List", year: 1993, hint: "Factory owner saves Jewish workers." },
    { title: "Raiders March", artist: "John Williams", movie: "Raiders of the Lost Ark", year: 1981, hint: "Archaeologist races Nazis to Ark." },
    { title: "The Map Room: Dawn", artist: "John Williams", movie: "Raiders of the Lost Ark", year: 1981, hint: "Indiana Jones hates snakes." },
    { title: "Flying Theme", artist: "John Williams", movie: "E.T. the Extra-Terrestrial", year: 1982, hint: "Alien botanist befriends Elliott." },
    { title: "Superman March", artist: "John Williams", movie: "Superman", year: 1978, hint: "Kryptonian hides as Clark Kent." },
    { title: "Jaws Theme", artist: "John Williams", movie: "Jaws", year: 1975, hint: "Sheriff hunts a great white shark." },
    { title: "Hymn to the Fallen", artist: "John Williams", movie: "Saving Private Ryan", year: 1998, hint: "Soldiers search for last surviving brother." },
    { title: "Somewhere in My Memory", artist: "John Williams", movie: "Home Alone", year: 1990, hint: "Boy left behind defends house." },
    { title: "Olympic Fanfare and Theme", artist: "John Williams", movie: "1984 Summer Olympics", year: 1984, hint: "Global athletic games in Los Angeles." },
    { title: "Close Encounters of the Third Kind", artist: "John Williams", movie: "Close Encounters of the Third Kind", year: 1977, hint: "Roy builds a mountain of mash." },
    
    // --- Hans Zimmer ---
    { title: "Time", artist: "Hans Zimmer", movie: "Inception", year: 2010, hint: "Thieves plant ideas in dreams." },
    { title: "Dream Is Collapsing", artist: "Hans Zimmer", movie: "Inception", year: 2010, hint: "DiCaprio spins a totem top." },
    { title: "Cornfield Chase", artist: "Hans Zimmer", movie: "Interstellar", year: 2014, hint: "Astronauts seek new home through wormhole." },
    { title: "No Time for Caution", artist: "Hans Zimmer", movie: "Interstellar", year: 2014, hint: "Murph solves gravity equation on earth." },
    { title: "The Dark Knight Theme", artist: "Hans Zimmer", movie: "The Dark Knight", year: 2008, hint: "Joker creates chaos in Gotham." },
    { title: "Gladiator Suite", artist: "Hans Zimmer", movie: "Gladiator", year: 2000, hint: "General becomes slave then gladiator." },
    { title: "Now We Are Free", artist: "Hans Zimmer", movie: "Gladiator", year: 2000, hint: "Maximus defies Emperor Commodus." },
    { title: "Chevaliers de Sangreal", artist: "Hans Zimmer", movie: "The Da Vinci Code", year: 2006, hint: "Symbologist investigates Louvre murder." },
    { title: "Discombobulate", artist: "Hans Zimmer", movie: "Sherlock Holmes", year: 2009, hint: "Detective fights Blackwood in London." },
    { title: "Driving Miss Daisy", artist: "Hans Zimmer", movie: "Driving Miss Daisy", year: 1989, hint: "Elderly woman befriends her chauffeur." },
    { title: "Paul's Dream", artist: "Hans Zimmer", movie: "Dune", year: 2021, hint: "Atreides family takes desert planet." },
    { title: "You're So Cool", artist: "Hans Zimmer", movie: "True Romance", year: 1993, hint: "Couple steals cocaine from pimp." },
    { title: "Lost but Won", artist: "Hans Zimmer", movie: "Rush", year: 2013, hint: "Rivalry between F1 drivers Hunt, Lauda." },

    // --- Ennio Morricone ---
    { title: "The Good, the Bad and the Ugly", artist: "Ennio Morricone", movie: "The Good, the Bad and the Ugly", year: 1966, hint: "Three gunslingers hunt buried gold." },
    { title: "The Ecstasy of Gold", artist: "Ennio Morricone", movie: "The Good, the Bad and the Ugly", year: 1966, hint: "Civil War backdrop for standoff." },
    { title: "Gabriel's Oboe", artist: "Ennio Morricone", movie: "The Mission", year: 1986, hint: "Jesuits protect tribe in South America." },
    { title: "On Earth As It Is In Heaven", artist: "Ennio Morricone", movie: "The Mission", year: 1986, hint: "De Niro plays penitant mercenary." },
    { title: "Cinema Paradiso", artist: "Ennio Morricone", movie: "Cinema Paradiso", year: 1988, hint: "Director recalls childhood movie theater." },
    { title: "Love Theme", artist: "Ennio Morricone", movie: "Cinema Paradiso", year: 1988, hint: "Projector operator blinds himself." },
    { title: "Chi Mai", artist: "Ennio Morricone", movie: "Le Professionnel", year: 1981, hint: "French agent betrayed by government." },
    { title: "L'Arena", artist: "Ennio Morricone", movie: "Kill Bill: Vol. 2", year: 2004, hint: "Assassin seeks revenge on Bill." },

    // --- John Barry ---
    { title: "John Dunbar Theme", artist: "John Barry", movie: "Dances with Wolves", year: 1990, hint: "Civil War soldier joins Sioux tribe." },
    { title: "Out of Africa", artist: "John Barry", movie: "Out of Africa", year: 1985, hint: "Baroness runs coffee plantation." },
    { title: "On Her Majesty's Secret Service", artist: "John Barry", movie: "On Her Majesty's Secret Service", year: 1969, hint: "Bond marries Tracy di Vicenzo." },
    { title: "Midnight Cowboy", artist: "John Barry", movie: "Midnight Cowboy", year: 1969, hint: "Hustler and con man in NYC." },
    { title: "Somewhere in Time", artist: "John Barry", movie: "Somewhere in Time", year: 1980, hint: "Playwright uses hypnosis to time travel." },

    // --- Jerry Goldsmith ---
    { title: "Ave Satani", artist: "Jerry Goldsmith", movie: "The Omen", year: 1976, hint: "Diplomat adopts the son of Satan." },
    { title: "Chinatown Theme", artist: "Jerry Goldsmith", movie: "Chinatown", year: 1974, hint: "PI investigates LA water scandal." },
    { title: "The Hunt", artist: "Jerry Goldsmith", movie: "Planet of the Apes", year: 1968, hint: "Astronauts land on ape world." },
    { title: "Star Trek: The Motion Picture", artist: "Jerry Goldsmith", movie: "Star Trek: The Motion Picture", year: 1979, hint: "Admiral Kirk retakes the Enterprise." },
    { title: "Carol Anne's Theme", artist: "Jerry Goldsmith", movie: "Poltergeist", year: 1982, hint: "Ghosts kidnap girl through TV." },

    // --- Howard Shore ---
    { title: "Concerning Hobbits", artist: "Howard Shore", movie: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, hint: "Frodo inherits a dangerous ring." },
    { title: "The Bridge of Khazad Dum", artist: "Howard Shore", movie: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, hint: "Fellowship travels through Moria mines." },
    { title: "Rohan", artist: "Howard Shore", movie: "The Lord of the Rings: The Two Towers", year: 2002, hint: "Ents attack Isengard tower." },
    { title: "The Lighting of the Beacons", artist: "Howard Shore", movie: "The Lord of the Rings: The Return of the King", year: 2003, hint: "Aragorn claims throne of Gondor." },

    // --- Alan Silvestri ---
    { title: "Feather Theme", artist: "Alan Silvestri", movie: "Forrest Gump", year: 1994, hint: "Slow man witnesses history." },
    { title: "Run Forrest Run", artist: "Alan Silvestri", movie: "Forrest Gump", year: 1994, hint: "Shrimping boat captain named Dan." },
    { title: "Back to the Future", artist: "Alan Silvestri", movie: "Back to the Future", year: 1985, hint: "Teen travels to 1955 in car." },
    { title: "The Avengers", artist: "Alan Silvestri", movie: "The Avengers", year: 2012, hint: "Superheroes team up against Loki." },
    { title: "Portals", artist: "Alan Silvestri", movie: "Avengers: Endgame", year: 2019, hint: "Thanos snaps half the universe." },
    { title: "Predator Theme", artist: "Alan Silvestri", movie: "Predator", year: 1987, hint: "Alien hunts commandos in jungle." },

    // --- James Horner ---
    { title: "Hymn to the Sea", artist: "James Horner", movie: "Titanic", year: 1997, hint: "Large ship sinks on maiden voyage." },
    { title: "Rose", artist: "James Horner", movie: "Titanic", year: 1997, hint: "Poor artist romances rich girl." },
    { title: "Braveheart Theme", artist: "James Horner", movie: "Braveheart", year: 1995, hint: "William Wallace fights for Scotland." },
    { title: "The Ludlows", artist: "James Horner", movie: "Legends of the Fall", year: 1994, hint: "Three brothers love same woman." },
    { title: "Becoming one of The People", artist: "James Horner", movie: "Avatar", year: 2009, hint: "Marine uses avatar on Pandora." },
    { title: "A Beautiful Mind", artist: "James Horner", movie: "A Beautiful Mind", year: 2001, hint: "Nash wins Nobel Prize in Economics." },
    { title: "Apollo 13 Theme", artist: "James Horner", movie: "Apollo 13", year: 1995, hint: "Astronauts survive explosion in space." },

    // --- Danny Elfman ---
    { title: "Spider-Man Main Title", artist: "Danny Elfman", movie: "Spider-Man", year: 2002, hint: "Student bitten by genetically altered spider." },
    { title: "Batman Theme", artist: "Danny Elfman", movie: "Batman", year: 1989, hint: "Vigilante fights Joker in Gotham." },
    { title: "Ice Dance", artist: "Danny Elfman", movie: "Edward Scissorhands", year: 1990, hint: "Suburban family takes in artificial man." },
    { title: "Introduction", artist: "Danny Elfman", movie: "Edward Scissorhands", year: 1990, hint: "Vincent Price created unfinished man." },
    { title: "Breakfast Machine", artist: "Danny Elfman", movie: "Pee-wee's Big Adventure", year: 1985, hint: "Man searches for stolen bike." },
    { title: "Beetlejuice Theme", artist: "Danny Elfman", movie: "Beetlejuice", year: 1988, hint: "Couple haunts their own house." },
    { title: "Men in Black", artist: "Danny Elfman", movie: "Men in Black", year: 1997, hint: "Secret agency polices aliens on Earth." },
    { title: "Alice's Theme", artist: "Danny Elfman", movie: "Alice in Wonderland", year: 2010, hint: "Girl returns to Underland." },

    // --- Vangelis ---
    { title: "Chariots of Fire", artist: "Vangelis", movie: "Chariots of Fire", year: 1981, hint: "British runners compete in 1924 Olympics." },
    { title: "Blade Runner Blues", artist: "Vangelis", movie: "Blade Runner", year: 1982, hint: "Cop hunts androids in future LA." },
    { title: "Tears in Rain", artist: "Vangelis", movie: "Blade Runner", year: 1982, hint: "Replicant Roy Batty saves Deckard." },
    { title: "Conquest of Paradise", artist: "Vangelis", movie: "1492: Conquest of Paradise", year: 1992, hint: "Depardieu plays Christopher Columbus." },

    // --- Classics & Others ---
    { title: "The Godfather Waltz", artist: "Nino Rota", movie: "The Godfather", year: 1972, hint: "Mafia family struggles with succession." },
    { title: "Love Theme", artist: "Nino Rota", movie: "The Godfather", year: 1972, hint: "Horse head found in bed." },
    { title: "Love Theme from Romeo and Juliet", artist: "Nino Rota", movie: "Romeo and Juliet", year: 1968, hint: "Feuding families Capulet and Montague." },
    { title: "Tara's Theme", artist: "Max Steiner", movie: "Gone with the Wind", year: 1939, hint: "Scarlett O'Hara survives Civil War." },
    { title: "Theme from A Summer Place", artist: "Percy Faith", movie: "A Summer Place", year: 1959, hint: "Adultery scandal at Maine inn." },
    { title: "The Pink Panther Theme", artist: "Henry Mancini", movie: "The Pink Panther", year: 1963, hint: "Inspector Clouseau tracks jewel thief." },
    { title: "Baby Elephant Walk", artist: "Henry Mancini", movie: "Hatari!", year: 1962, hint: "Zoo catchers in East Africa." },
    { title: "Psycho (The Murder)", artist: "Bernard Herrmann", movie: "Psycho", year: 1960, hint: "Motel owner keeps mother's corpse." },
    { title: "Vertigo Prelude", artist: "Bernard Herrmann", movie: "Vertigo", year: 1958, hint: "Detective obsessed with mysterious blonde." },
    { title: "Taxi Driver Theme", artist: "Bernard Herrmann", movie: "Taxi Driver", year: 1976, hint: "Insomniac cabbie plots assassination." },
    { title: "North by Northwest Overture", artist: "Bernard Herrmann", movie: "North by Northwest", year: 1959, hint: "Ad man mistaken for spy." },
    { title: "Also Sprach Zarathustra", artist: "Richard Strauss", movie: "2001: A Space Odyssey", year: 1968, hint: "HAL 9000 refuses to open doors." },
    { title: "The Magnificent Seven", artist: "Elmer Bernstein", movie: "The Magnificent Seven", year: 1960, hint: "Seven gunmen protect Mexican village." },
    { title: "The Great Escape", artist: "Elmer Bernstein", movie: "The Great Escape", year: 1963, hint: "POWs tunnel out of camp." },
    { title: "To Kill a Mockingbird", artist: "Elmer Bernstein", movie: "To Kill a Mockingbird", year: 1962, hint: "Lawyer defends black man in south." },
    { title: "Halloween Theme", artist: "John Carpenter", movie: "Halloween", year: 1978, hint: "Jamie Lee Curtis fights masked killer." },
    { title: "Escape from New York", artist: "John Carpenter", movie: "Escape from New York", year: 1981, hint: "Manhattan is a giant prison." },
    { title: "Tubular Bells", artist: "Mike Oldfield", movie: "The Exorcist", year: 1973, hint: "Priests perform exorcism on girl." },
    { title: "Mission: Impossible", artist: "Lalo Schifrin", movie: "Mission: Impossible", year: 1996, hint: "Ethan Hunt uncovers a mole." },
    { title: "007 Theme", artist: "Monty Norman", movie: "Dr. No", year: 1962, hint: "First James Bond film released." },
    { title: "Rocky's Reward", artist: "Bill Conti", movie: "Rocky", year: 1976, hint: "Small time boxer gets title shot." },
    { title: "Going the Distance", artist: "Bill Conti", movie: "Rocky", year: 1976, hint: "Underdog boxer trains with meat." },
    { title: "The Right Stuff", artist: "Bill Conti", movie: "The Right Stuff", year: 1983, hint: "Test pilots become first astronauts." },
    { title: "Lawrence of Arabia Overture", artist: "Maurice Jarre", movie: "Lawrence of Arabia", year: 1962, hint: "British officer unites Arab tribes." },
    { title: "Lara's Theme", artist: "Maurice Jarre", movie: "Doctor Zhivago", year: 1965, hint: "Doctor writes poetry during revolution." },
    { title: "Axel F", artist: "Harold Faltermeyer", movie: "Beverly Hills Cop", year: 1984, hint: "Detroit cop investigates murder in LA." },
    { title: "Top Gun Anthem", artist: "Harold Faltermeyer", movie: "Top Gun", year: 1986, hint: "Navy pilots compete at school." },
    { title: "Terminator Theme", artist: "Brad Fiedel", movie: "The Terminator", year: 1984, hint: "Cyborg sent back to kill Sarah." },
    { title: "RoboCop Theme", artist: "Basil Poledouris", movie: "RoboCop", year: 1987, hint: "Dead cop resurrected as cyborg." },
    { title: "Anvil of Crom", artist: "Basil Poledouris", movie: "Conan the Barbarian", year: 1982, hint: "Barbarian seeks revenge for parents." },
    { title: "Hymn to Red October", artist: "Basil Poledouris", movie: "The Hunt for Red October", year: 1990, hint: "Soviet captain defects with submarine." },
    { title: "Merry-Go-Round of Life", artist: "Joe Hisaishi", movie: "Howl's Moving Castle", year: 2004, hint: "Girl works in a walking castle." },
    { title: "One Summer's Day", artist: "Joe Hisaishi", movie: "Spirited Away", year: 2001, hint: "Girl trapped in spirit world." },
    { title: "Path of the Wind", artist: "Joe Hisaishi", movie: "My Neighbor Totoro", year: 1988, hint: "Sisters befriend forest spirits." },
    { title: "Legend of Ashitaka", artist: "Joe Hisaishi", movie: "Princess Mononoke", year: 1997, hint: "Nature spirits fight human industry." },
    { title: "He's a Pirate", artist: "Klaus Badelt", movie: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003, hint: "Blacksmith teams up with pirate." },
    { title: "The Black Pearl", artist: "Klaus Badelt", movie: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003, hint: "Cursed pirates turn into skeletons." },
    { title: "Mia and Sebastian's Theme", artist: "Justin Hurwitz", movie: "La La Land", year: 2016, hint: "Musician and actress chase dreams." },
    { title: "Planetarium", artist: "Justin Hurwitz", movie: "La La Land", year: 2016, hint: "Couple floats in observatory." },
    { title: "Married Life", artist: "Michael Giacchino", movie: "Up", year: 2009, hint: "Old man flies house with balloons." },
    { title: "Life's Incredible Again", artist: "Michael Giacchino", movie: "The Incredibles", year: 2004, hint: "Family of superheroes fights Syndrome." },
    { title: "Star Trek Main Theme", artist: "Michael Giacchino", movie: "Star Trek", year: 2009, hint: "Romulan Nero destroys Vulcan." },
    { title: "The Batman Theme", artist: "Michael Giacchino", movie: "The Batman", year: 2022, hint: "Riddler kills corrupt Gotham elites." },
    { title: "The Shape of Water", artist: "Alexandre Desplat", movie: "The Shape of Water", year: 2017, hint: "Mute woman frees aquatic creature." },
    { title: "The Imitation Game", artist: "Alexandre Desplat", movie: "The Imitation Game", year: 2014, hint: "Mathematician hides his sexuality." },
    { title: "Mr. Moustafa", artist: "Alexandre Desplat", movie: "The Grand Budapest Hotel", year: 2014, hint: "Lobby boy inherits a hotel." },
    { title: "American Beauty", artist: "Thomas Newman", movie: "American Beauty", year: 1999, hint: "Man obsessed with daughter's friend." },
    { title: "Nemo Egg", artist: "Thomas Newman", movie: "Finding Nemo", year: 2003, hint: "Fish swims to Sydney harbor." },
    { title: "Brooks Was Here", artist: "Thomas Newman", movie: "The Shawshank Redemption", year: 1994, hint: "Banker wrongly imprisoned for murder." },
    { title: "The Night Window", artist: "Thomas Newman", movie: "1917", year: 2019, hint: "Soldiers deliver message across trenches." },
    { title: "Hand Covers Bruise", artist: "Trent Reznor & Atticus Ross", movie: "The Social Network", year: 2010, hint: "Harvard student sued by twins." },
    { title: "On the Nature of Daylight", artist: "Max Richter", movie: "Arrival", year: 2016, hint: "Linguist communicates with heptapods." },
    { title: "Wakanda", artist: "Ludwig Göransson", movie: "Black Panther", year: 2018, hint: "Prince challenges cousin for throne." },
    { title: "Can You Hear the Music", artist: "Ludwig Göransson", movie: "Oppenheimer", year: 2023, hint: "Scientist leads Manhattan Project." },
    { title: "Posterity", artist: "Ludwig Göransson", movie: "Tenet", year: 2020, hint: "Protagonist fights future war." },
    { title: "Bathroom Dance", artist: "Hildur Guðnadóttir", movie: "Joker", year: 2019, hint: "Failed comedian descends into madness." },
    { title: "Amélie Waltz", artist: "Yann Tiersen", movie: "Amélie", year: 2001, hint: "Waitress orchestrates happiness for others." },
    { title: "Comptine d'un autre été", artist: "Yann Tiersen", movie: "Amélie", year: 2001, hint: "Girl finds tin box in wall." },
    { title: "Crouching Tiger, Hidden Dragon", artist: "Tan Dun", movie: "Crouching Tiger, Hidden Dragon", year: 2000, hint: "Swordsman gives up Green Destiny." },
    { title: "Test Drive", artist: "John Powell", movie: "How to Train Your Dragon", year: 2010, hint: "Viking boy befriends a dragon." },
    { title: "Romantic Flight", artist: "John Powell", movie: "How to Train Your Dragon", year: 2010, hint: "Dragons nest in volcano." },
    { title: "Forbidden Friendship", artist: "John Powell", movie: "How to Train Your Dragon", year: 2010, hint: "Boy makes tail for dragon." },
    { title: "Lux Aeterna", artist: "Clint Mansell", movie: "Requiem for a Dream", year: 2000, hint: "Four people ruined by drugs." },
    { title: "Promontory", artist: "Trevor Jones", movie: "The Last of the Mohicans", year: 1992, hint: "Hawkeye protects Colonel's daughters." },
    { title: "Misirlou", artist: "Dick Dale", movie: "Pulp Fiction", year: 1994, hint: "Hitmen retrieve a briefcase." },
    { title: "Dueling Banjos", artist: "Eric Weissberg", movie: "Deliverance", year: 1972, hint: "Locals terrorize city men canoeing." },
    { title: "The Entertainer", artist: "Marvin Hamlisch", movie: "The Sting", year: 1973, hint: "Grifters swindle a mob boss." },
    { title: "Cavatina", artist: "John Williams (Guitarist)", movie: "The Deer Hunter", year: 1978, hint: "Steelworkers go to Vietnam." },
    { title: "Theme from Love Story", artist: "Francis Lai", movie: "Love Story", year: 1970, hint: "Harvard student marries dying girl." },
    { title: "Arrival to Earth", artist: "Steve Jablonsky", movie: "Transformers", year: 2007, hint: "Boy buys car that is robot." },
    { title: "Truman Sleeps", artist: "Philip Glass", movie: "The Truman Show", year: 1998, hint: "Man discovers life is fake." },
    { title: "Dawn", artist: "Dario Marianelli", movie: "Pride & Prejudice", year: 2005, hint: "Bennet sisters need rich husbands." },
    { title: "Merry Christmas Mr. Lawrence", artist: "Ryuichi Sakamoto", movie: "Merry Christmas, Mr. Lawrence", year: 1983, hint: "British soldier defies camp commander." },
    { title: "The Last Emperor (Theme)", artist: "Ryuichi Sakamoto", movie: "The Last Emperor", year: 1987, hint: "Life of China's final monarch." },
    { title: "Battle Without Honor or Humanity", artist: "Tomoyasu Hotei", movie: "Kill Bill: Vol. 1", year: 2003, hint: "The Bride fights Crazy 88." },
    { title: "Clubbed to Death", artist: "Rob Dougan", movie: "The Matrix", year: 1999, hint: "Hacker learns reality is simulation." },
    { title: "In the House - In a Heartbeat", artist: "John Murphy", movie: "28 Days Later", year: 2002, hint: "Rage virus destroys Great Britain." },
    { title: "Adagio in D Minor", artist: "John Murphy", movie: "Sunshine", year: 2007, hint: "Space crew reignites the sun." },
    { title: "Pacific Rim", artist: "Ramin Djawadi", movie: "Pacific Rim", year: 2013, hint: "Pilots drift to control Jaegers." }
  ],
  animated_films: [ // Instrumental scores AND songs with vocals allowed.
    // --- Disney Renaissance & Golden Age ---
    { title: "Circle of Life", artist: "Elton John", movie: "The Lion King", year: 1994, hint: "Lion cub is born to be king." },
    { title: "Hakuna Matata", artist: "Nathan Lane", movie: "The Lion King", year: 1994, hint: "Warthog and meerkat raise a lion." },
    { title: "Can You Feel the Love Tonight", artist: "Elton John", movie: "The Lion King", year: 1994, hint: "Simba returns to challenge his uncle." },
    { title: "Under the Sea", artist: "Samuel E. Wright", movie: "The Little Mermaid", year: 1989, hint: "Mermaid wants to live on land." },
    { title: "Part of Your World", artist: "Jodi Benson", movie: "The Little Mermaid", year: 1989, hint: "King Triton's daughter loves human objects." },
    { title: "Kiss the Girl", artist: "Samuel E. Wright", movie: "The Little Mermaid", year: 1989, hint: "Ursula gives mermaid legs for voice." },
    { title: "Beauty and the Beast", artist: "Angela Lansbury", movie: "Beauty and the Beast", year: 1991, hint: "Village girl is prisoner in castle." },
    { title: "Be Our Guest", artist: "Jerry Orbach", movie: "Beauty and the Beast", year: 1991, hint: "Cursed household objects serve a guest." },
    { title: "Belle", artist: "Paige O'Hara", movie: "Beauty and the Beast", year: 1991, hint: "Bookworm girl wants more than provincial life." },
    { title: "A Whole New World", artist: "Brad Kane", movie: "Aladdin", year: 1992, hint: "Street rat finds a magic lamp." },
    { title: "Friend Like Me", artist: "Robin Williams", movie: "Aladdin", year: 1992, hint: "Jafar wants the lamp from the cave." },
    { title: "Prince Ali", artist: "Robin Williams", movie: "Aladdin", year: 1992, hint: "Aladdin wishes to be a prince." },
    { title: "Colors of the Wind", artist: "Judy Kuhn", movie: "Pocahontas", year: 1995, hint: "Native American woman meets English settler." },
    { title: "Just Around the Riverbend", artist: "Judy Kuhn", movie: "Pocahontas", year: 1995, hint: "Smith and Pocahontas bridge two worlds." },
    { title: "You'll Be in My Heart", artist: "Phil Collins", movie: "Tarzan", year: 1999, hint: "Man raised by apes meets humans." },
    { title: "Strangers Like Me", artist: "Phil Collins", movie: "Tarzan", year: 1999, hint: "Jane Porter explores the African jungle." },
    { title: "Son of Man", artist: "Phil Collins", movie: "Tarzan", year: 1999, hint: "Leopard Sabor hunts the ape family." },
    { title: "Two Worlds", artist: "Phil Collins", movie: "Tarzan", year: 1999, hint: "Clayton wants to capture the gorillas." },
    { title: "I'll Make a Man Out of You", artist: "Donny Osmond", movie: "Mulan", year: 1998, hint: "Girl disguises as man for army." },
    { title: "Reflection", artist: "Lea Salonga", movie: "Mulan", year: 1998, hint: "Fa Mulan saves China from Huns." },
    { title: "Honor to Us All", artist: "Lea Salonga", movie: "Mulan", year: 1998, hint: "Matchmaker rejects a clumsy young woman." },
    { title: "Go the Distance", artist: "Roger Bart", movie: "Hercules", year: 1997, hint: "Strong man seeks his god father." },
    { title: "Zero to Hero", artist: "Lillias White", movie: "Hercules", year: 1997, hint: "Hades tries to kill Zeus's son." },
    { title: "I Won't Say (I'm in Love)", artist: "Susan Egan", movie: "Hercules", year: 1997, hint: "Demi-god trains with satyr Phil." },
    { title: "God Help the Outcasts", artist: "Heidi Mollenhauer", movie: "The Hunchback of Notre Dame", year: 1996, hint: "Gypsy dancer befriends a bell ringer." },
    { title: "Out There", artist: "Tony Jay", movie: "The Hunchback of Notre Dame", year: 1996, hint: "Hunchback lives in Notre Dame Cathedral." },
    { title: "The Bare Necessities", artist: "Phil Harris", movie: "The Jungle Book", year: 1967, hint: "Boy raised by wolves fights tiger." },
    { title: "I Wan'na Be Like You", artist: "Louis Prima", movie: "The Jungle Book", year: 1967, hint: "Panther and bear escort a man-cub." },
    { title: "Bibbidi-Bobbidi-Boo", artist: "Verna Felton", movie: "Cinderella", year: 1950, hint: "Girl loses glass slipper at ball." },
    { title: "A Dream Is a Wish Your Heart Makes", artist: "Ilene Woods", movie: "Cinderella", year: 1950, hint: "Stepmother treats girl like a servant." },
    { title: "When You Wish Upon a Star", artist: "Cliff Edwards", movie: "Pinocchio", year: 1940, hint: "Puppet wants to be real boy." },
    { title: "Whistle While You Work", artist: "Adriana Caselotti", movie: "Snow White and the Seven Dwarfs", year: 1937, hint: "Princess lives with seven miners." },
    { title: "Heigh-Ho", artist: "The Dwarfs", movie: "Snow White and the Seven Dwarfs", year: 1937, hint: "Queen wants Snow White's heart." },
    { title: "Once Upon a Dream", artist: "Mary Costa", movie: "Sleeping Beauty", year: 1959, hint: "Maleficent curses a baby princess." },
    { title: "Cruella De Vil", artist: "Bill Lee", movie: "One Hundred and One Dalmatians", year: 1961, hint: "Woman wants coat made of puppies." },
    { title: "Bella Notte", artist: "George Givot", movie: "Lady and the Tramp", year: 1955, hint: "Cocker Spaniel falls for a stray." },
    { title: "You Can Fly! You Can Fly!", artist: "Bobby Driscoll", movie: "Peter Pan", year: 1953, hint: "Boy who never grows up visits London." },
    { title: "Everybody Wants to Be a Cat", artist: "Scatman Crothers", movie: "The Aristocats", year: 1970, hint: "Butler kidnaps kittens for inheritance." },
    { title: "Hawaiian Roller Coaster Ride", artist: "Mark Keali'i Ho'omalu", movie: "Lilo & Stitch", year: 2002, hint: "Blue alien crashes in Hawaii." },
    { title: "He Mele No Lilo", artist: "Mark Keali'i Ho'omalu", movie: "Lilo & Stitch", year: 2002, hint: "Girl adopts a destructive alien dog." },
    { title: "I'm Still Here", artist: "John Rzeznik", movie: "Treasure Planet", year: 2002, hint: "Cyborg cook seeks treasure planet." },
    { title: "On My Way", artist: "Phil Collins", movie: "Brother Bear", year: 2003, hint: "Man turns into bear to learn." },
    { title: "My Funny Friend and Me", artist: "Sting", movie: "The Emperor's New Groove", year: 2000, hint: "Emperor turned into llama by Yzma." },
    { title: "Why Should I Worry?", artist: "Billy Joel", movie: "Oliver & Company", year: 1988, hint: "Orphan kitten joins dog gang." },
    { title: "I2I", artist: "Tevin Campbell", movie: "A Goofy Movie", year: 1995, hint: "Father and son go on roadtrip." },
    { title: "Stand Out", artist: "Tevin Campbell", movie: "A Goofy Movie", year: 1995, hint: "Goofy takes Max fishing." },
    { title: "Oo-De-Lally", artist: "Roger Miller", movie: "Robin Hood", year: 1973, hint: "Outlaw fox steals from the rich." },
    
    // --- Pixar ---
    { title: "You've Got a Friend in Me", artist: "Randy Newman", movie: "Toy Story", year: 1995, hint: "Toys come to life when unseen." },
    { title: "I Will Go Sailing No More", artist: "Randy Newman", movie: "Toy Story", year: 1995, hint: "Astronaut toy thinks he's real." },
    { title: "Strange Things", artist: "Randy Newman", movie: "Toy Story", year: 1995, hint: "Cowboy doll replaced by space toy." },
    { title: "When She Loved Me", artist: "Sarah McLachlan", movie: "Toy Story 2", year: 1999, hint: "Toy collector steals Woody." },
    { title: "Woody's Roundup", artist: "Riders in the Sky", movie: "Toy Story 2", year: 1999, hint: "Cowgirl toy has abandonment issues." },
    { title: "We Belong Together", artist: "Randy Newman", movie: "Toy Story 3", year: 2010, hint: "Toys mistakenly sent to daycare." },
    { title: "Married Life", artist: "Michael Giacchino", movie: "Up", year: 2009, hint: "Boy scout stowaway on flying house." },
    { title: "The Incredibles Suite", artist: "Michael Giacchino", movie: "The Incredibles", year: 2004, hint: "Family of superheroes fights Syndrome." },
    { title: "Life's Incredible Again", artist: "Michael Giacchino", movie: "The Incredibles", year: 2004, hint: "Superhero dad has midlife crisis." },
    { title: "If I Didn't Have You", artist: "Billy Crystal", movie: "Monsters, Inc.", year: 2001, hint: "Monsters power city with children's screams." },
    { title: "The Scare Floor", artist: "Randy Newman", movie: "Monsters, Inc.", year: 2001, hint: "Little girl enters monster world." },
    { title: "Remember Me", artist: "Benjamin Bratt", movie: "Coco", year: 2017, hint: "Boy visits Land of the Dead." },
    { title: "Un Poco Loco", artist: "Anthony Gonzalez", movie: "Coco", year: 2017, hint: "Musician seeks great-grandfather's blessing." },
    { title: "Proud Corazón", artist: "Anthony Gonzalez", movie: "Coco", year: 2017, hint: "Family bans music for generations." },
    { title: "Le Festin", artist: "Camille", movie: "Ratatouille", year: 2007, hint: "Rat wants to be a chef." },
    { title: "Nemo Egg", artist: "Thomas Newman", movie: "Finding Nemo", year: 2003, hint: "Fish swims to Sydney harbor." },
    { title: "Beyond the Sea", artist: "Robbie Williams", movie: "Finding Nemo", year: 2003, hint: "Clownfish father searches for son." },
    { title: "Life is a Highway", artist: "Rascal Flatts", movie: "Cars", year: 2006, hint: "Racecar gets stuck in small town." },
    { title: "Real Gone", artist: "Sheryl Crow", movie: "Cars", year: 2006, hint: "Rookie racecar learns from old pro." },
    { title: "Our Town", artist: "James Taylor", movie: "Cars", year: 2006, hint: "Route 66 town forgotten by interstate." },
    { title: "Touch the Sky", artist: "Julie Fowlis", movie: "Brave", year: 2012, hint: "Scottish princess turns mom into bear." },
    { title: "Nobody Like U", artist: "4*TOWN", movie: "Turning Red", year: 2022, hint: "Girl turns into giant red panda." },
    { title: "Steal the Show", artist: "Lauv", movie: "Elemental", year: 2023, hint: "Fire girl loves water boy." },
    { title: "Down to Earth", artist: "Peter Gabriel", movie: "WALL-E", year: 2008, hint: "Trash robot falls for sleek probe." },
    { title: "Bundle of Joy", artist: "Michael Giacchino", movie: "Inside Out", year: 2015, hint: "Emotions control girl's mind." },
    { title: "It's All Right", artist: "Jon Batiste", movie: "Soul", year: 2020, hint: "Musician dies before big break." },

    // --- Modern Disney (Frozen/Moana/Encanto) ---
    { title: "Let It Go", artist: "Idina Menzel", movie: "Frozen", year: 2013, hint: "Queen with ice powers flees kingdom." },
    { title: "Do You Want to Build a Snowman?", artist: "Kristen Bell", movie: "Frozen", year: 2013, hint: "Sisters separated by icy magic powers." },
    { title: "For the First Time in Forever", artist: "Kristen Bell", movie: "Frozen", year: 2013, hint: "Eternal winter plagues the fjord kingdom." },
    { title: "Love Is an Open Door", artist: "Kristen Bell", movie: "Frozen", year: 2013, hint: "Anna seeks her sister on mountain." },
    { title: "Into the Unknown", artist: "Idina Menzel", movie: "Frozen II", year: 2019, hint: "Spirits of the Enchanted Forest call." },
    { title: "Show Yourself", artist: "Idina Menzel", movie: "Frozen II", year: 2019, hint: "Sisters solve mystery of parents' death." },
    { title: "How Far I'll Go", artist: "Auli'i Cravalho", movie: "Moana", year: 2016, hint: "Girl returns heart to island goddess." },
    { title: "You're Welcome", artist: "Dwayne Johnson", movie: "Moana", year: 2016, hint: "Demigod helps girl cross the ocean." },
    { title: "Shiny", artist: "Jemaine Clement", movie: "Moana", year: 2016, hint: "Chicken accompanies girl on raft." },
    { title: "We Don't Talk About Bruno", artist: "Encanto Cast", movie: "Encanto", year: 2021, hint: "Magic house cracks in Colombia." },
    { title: "Surface Pressure", artist: "Jessica Darrow", movie: "Encanto", year: 2021, hint: "Family receives gifts from a candle." },
    { title: "Dos Oruguitas", artist: "Sebastián Yatra", movie: "Encanto", year: 2021, hint: "Girl tries to save family miracle." },
    { title: "The Family Madrigal", artist: "Stephanie Beatriz", movie: "Encanto", year: 2021, hint: "House casita comes to life." },
    { title: "I See the Light", artist: "Mandy Moore", movie: "Tangled", year: 2010, hint: "Girl with long hair leaves tower." },
    { title: "When Will My Life Begin?", artist: "Mandy Moore", movie: "Tangled", year: 2010, hint: "Thief Flynn Rider steals a crown." },
    { title: "Almost There", artist: "Anika Noni Rose", movie: "The Princess and the Frog", year: 2009, hint: "Waitress and prince turn into frogs." },
    { title: "Friends on the Other Side", artist: "Keith David", movie: "The Princess and the Frog", year: 2009, hint: "Shadow man makes deal in New Orleans." },
    { title: "Dig a Little Deeper", artist: "Jenifer Lewis", movie: "The Princess and the Frog", year: 2009, hint: "Jazz loving alligator plays trumpet." },
    { title: "Down in New Orleans", artist: "Dr. John", movie: "The Princess and the Frog", year: 2009, hint: "Hardworking girl wants a restaurant." },
    { title: "Try Everything", artist: "Shakira", movie: "Zootopia", year: 2016, hint: "Fox and rabbit solve predator mystery." },
    { title: "Immortals", artist: "Fall Out Boy", movie: "Big Hero 6", year: 2014, hint: "Inflatable robot cares for boy's health." },
    { title: "When Can I See You Again?", artist: "Owl City", movie: "Wreck-It Ralph", year: 2012, hint: "Bad guy wants to be a hero." },
    { title: "This Wish", artist: "Ariana DeBose", movie: "Wish", year: 2023, hint: "King Magnifico hoards wishes." },

    // --- Dreamworks & Others ---
    { title: "All Star", artist: "Smash Mouth", movie: "Shrek", year: 2001, hint: "Ogre rescues princess from dragon." },
    { title: "I'm a Believer", artist: "Smash Mouth", movie: "Shrek", year: 2001, hint: "Talking donkey annoys green ogre." },
    { title: "Hallelujah", artist: "Rufus Wainwright", movie: "Shrek", year: 2001, hint: "Lord Farquaad wants to marry Fiona." },
    { title: "Accidentally in Love", artist: "Counting Crows", movie: "Shrek 2", year: 2004, hint: "Ogre meets his royal in-laws." },
    { title: "Peaches", artist: "Jack Black", movie: "The Super Mario Bros. Movie", year: 2023, hint: "Plumber brothers fight giant turtle." },

    // --- Studio Ghibli ---
    { title: "A Town with an Ocean View", artist: "Joe Hisaishi", movie: "Kiki's Delivery Service", year: 1989, hint: "Young witch starts delivery service." },
    { title: "My Neighbor Totoro", artist: "Azumi Inoue", movie: "My Neighbor Totoro", year: 1988, hint: "Sisters befriend giant forest spirit." },
    { title: "Path of the Wind", artist: "Joe Hisaishi", movie: "My Neighbor Totoro", year: 1988, hint: "Catbus transports girls to mom." },
    { title: "Ponyo on the Cliff by the Sea", artist: "Fujioka Fujimaki & Nozomi Ohashi", movie: "Ponyo", year: 2008, hint: "Goldfish princess wants to be human." },
    { title: "Carrying You", artist: "Azumi Inoue", movie: "Castle in the Sky", year: 1986, hint: "Orphans search for floating city." },
    { title: "One Summer's Day", artist: "Joe Hisaishi", movie: "Spirited Away", year: 2001, hint: "Girl works in spirit bathhouse." },
    { title: "Always With Me", artist: "Youmi Kimura", movie: "Spirited Away", year: 2001, hint: "Parents turn into pigs." },
    { title: "Merry-Go-Round of Life", artist: "Joe Hisaishi", movie: "Howl's Moving Castle", year: 2004, hint: "Cursed girl lives in walking castle." },
    { title: "The Promise of the World", artist: "Chieko Baisho", movie: "Howl's Moving Castle", year: 2004, hint: "Wizard eats a falling star." },
    { title: "Princess Mononoke", artist: "Yoshikazu Mera", movie: "Princess Mononoke", year: 1997, hint: "Prince cursed by a boar demon." },
    { title: "Legend of Ashitaka", artist: "Joe Hisaishi", movie: "Princess Mononoke", year: 1997, hint: "Girl raised by wolves fights industry." },
    { title: "Nausicaä of the Valley of the Wind", artist: "Joe Hisaishi", movie: "Nausicaä of the Valley of the Wind", year: 1984, hint: "Princess calms giant Ohmu insects." },
    { title: "Country Roads", artist: "Yoko Honna", movie: "Whisper of the Heart", year: 1995, hint: "Girl writes story about cat baron." },
    { title: "Arrietty's Song", artist: "Cécile Corbel", movie: "The Secret World of Arrietty", year: 2010, hint: "Tiny people borrow human items." },
    { title: "Fine On The Outside", artist: "Priscilla Ahn", movie: "When Marnie Was There", year: 2014, hint: "Girl befriends a ghost in mansion." }
  ],
  modern_tv: [ // Intro themes only. Shows airing 2000 onwards (Live Action Only).
    // --- Prestige Drama ---
    { title: "Game of Thrones Main Title", artist: "Ramin Djawadi", movie: "Game of Thrones", year: 2011, hint: "Noble families fight for Iron Throne." },
    { title: "Succession (Main Title)", artist: "Nicholas Britell", movie: "Succession", year: 2018, hint: "Media mogul's kids want power." },
    { title: "The White Lotus Theme", artist: "Cristobal Tapia de Veer", movie: "The White Lotus", year: 2021, hint: "Rich tourists create chaos at resort." },
    { title: "Breaking Bad Theme", artist: "Dave Porter", movie: "Breaking Bad", year: 2008, hint: "Chemistry teacher cooks blue meth." },
    { title: "Better Call Saul Theme", artist: "Little Barrie", movie: "Better Call Saul", year: 2015, hint: "Conman lawyer defends criminals." },
    { title: "A Beautiful Mine", artist: "RJD2", movie: "Mad Men", year: 2007, hint: "Advertising executives in 1960s NYC." },
    { title: "Woke Up This Morning", artist: "Alabama 3", movie: "The Sopranos", year: 1999, hint: "Mob boss sees a psychiatrist." },
    { title: "Way Down in the Hole", artist: "The Blind Boys of Alabama", movie: "The Wire", year: 2002, hint: "Police wiretap Baltimore drug gangs." },
    { title: "Dexter Main Title", artist: "Rolfe Kent", movie: "Dexter", year: 2006, hint: "Blood spatter analyst is serial killer." },
    { title: "Lost Main Title", artist: "Michael Giacchino", movie: "Lost", year: 2004, hint: "Survivors trapped on mysterious island." },
    { title: "Downton Abbey Theme", artist: "John Lunn", movie: "Downton Abbey", year: 2010, hint: "Aristocrats and servants in early 1900s." },
    { title: "The Crown Main Title", artist: "Hans Zimmer", movie: "The Crown", year: 2016, hint: "Life of Queen Elizabeth II." },
    { title: "Westworld Main Title", artist: "Ramin Djawadi", movie: "Westworld", year: 2016, hint: "Android hosts rebel in theme park." },
    { title: "House of Cards Theme", artist: "Jeff Beal", movie: "House of Cards", year: 2013, hint: "Ruthless politician seeks presidency." },
    { title: "Homeland Theme", artist: "Sean Callery", movie: "Homeland", year: 2011, hint: "CIA agent suspects returned POW." },
    { title: "This Is Us Theme", artist: "Siddhartha Khosla", movie: "This Is Us", year: 2016, hint: "Triplets navigate life and family." },
    { title: "Yellowstone Theme", artist: "Brian Tyler", movie: "Yellowstone", year: 2018, hint: "Family defends largest ranch in Montana." },
    { title: "Severance Main Title", artist: "Theodore Shapiro", movie: "Severance", year: 2022, hint: "Employees split work and personal memories." },
    { title: "The Handmaid's Tale Theme", artist: "Adam Taylor", movie: "The Handmaid's Tale", year: 2017, hint: "Fertile women enslaved in Gilead." },
    { title: "Big Little Lies Theme", artist: "Michael Kiwanuka", movie: "Big Little Lies", year: 2017, hint: "Mothers cover up a murder." },
    { title: "True Detective Theme", artist: "The Handsome Family", movie: "True Detective", year: 2014, hint: "Detectives hunt serial killer over decades." },
    { title: "Fargo Theme", artist: "Jeff Russo", movie: "Fargo", year: 2014, hint: "Anthology of crimes in frozen Midwest." },
    { title: "Peaky Blinders Theme", artist: "Nick Cave", movie: "Peaky Blinders", year: 2013, hint: "Gangster family in post-WWI England." },
    { title: "Mr. Robot Theme", artist: "Mac Quayle", movie: "Mr. Robot", year: 2015, hint: "Hacker aims to erase debt." },
    { title: "Tuyo (Narcos Theme)", artist: "Rodrigo Amarante", movie: "Narcos", year: 2015, hint: "DEA agents hunt Pablo Escobar." },
    { title: "Squid Game Theme", artist: "Jung Jae-il", movie: "Squid Game", year: 2021, hint: "Debtors play deadly children's games." },
    { title: "The Last of Us Theme", artist: "Gustavo Santaolalla", movie: "The Last of Us", year: 2023, hint: "Smuggler escorts immune girl across US." },
    { title: "House of the Dragon Theme", artist: "Ramin Djawadi", movie: "House of the Dragon", year: 2022, hint: "Civil war splits Targaryen family." },
    { title: "Succession Theme", artist: "Nicholas Britell", movie: "Succession", year: 2018, hint: "Logan Roy's kids want company." },
    { title: "Ozark Theme", artist: "Danny Bensi", movie: "Ozark", year: 2017, hint: "Family launders money for cartel." },
    { title: "Mindhunter Theme", artist: "Jason Hill", movie: "Mindhunter", year: 2017, hint: "FBI agents study serial psychology." },

    // --- Comedy/Sitcom (Live Action) ---
    { title: "The Office Theme", artist: "The Scrantones", movie: "The Office (US)", year: 2005, hint: "Mockumentary of paper supply company." },
    { title: "Parks and Recreation Theme", artist: "Gaby Moreno", movie: "Parks and Recreation", year: 2009, hint: "Public officials in Pawnee, Indiana." },
    { title: "30 Rock Theme", artist: "Jeff Richmond", movie: "30 Rock", year: 2006, hint: "Chaos behind an NBC sketch show." },
    { title: "At Least It Was Here", artist: "The 88", movie: "Community", year: 2009, hint: "Misfits form community college study group." },
    { title: "Arrested Development Theme", artist: "David Schwartz", movie: "Arrested Development", year: 2003, hint: "Wealthy family loses everything." },
    { title: "Modern Family Theme", artist: "Gabriel Mann", movie: "Modern Family", year: 2009, hint: "Three related families face daily life." },
    { title: "Hey Beautiful", artist: "The Solids", movie: "How I Met Your Mother", year: 2005, hint: "Dad tells kids how he met mom." },
    { title: "The History of Everything", artist: "Barenaked Ladies", movie: "The Big Bang Theory", year: 2007, hint: "Nerds befriend waitress neighbor." },
    { title: "Brooklyn Nine-Nine", artist: "Dan Marocco", movie: "Brooklyn Nine-Nine", year: 2013, hint: "Detectives crack jokes in precinct." },
    { title: "Ted Lasso Theme", artist: "Marcus Mumford", movie: "Ted Lasso", year: 2020, hint: "Optimistic coach leads British soccer team." },
    { title: "Where You Lead", artist: "Carole King", movie: "Gilmore Girls", year: 2000, hint: "Mother and daughter in Stars Hollow." },
    { title: "Superman", artist: "Lazlo Bane", movie: "Scrubs", year: 2001, hint: "Interns learn at teaching hospital." },
    { title: "Frolic (Curb Theme)", artist: "Luciano Michelini", movie: "Curb Your Enthusiasm", year: 2000, hint: "TV writer navigates social awkwardness." },
    { title: "Boss of Me", artist: "They Might Be Giants", movie: "Malcolm in the Middle", year: 2000, hint: "Gifted kid in dysfunctional family." },
    { title: "Hey Girl", artist: "Zooey Deschanel", movie: "New Girl", year: 2011, hint: "Teacher moves in with three bachelors." },
    { title: "It's a Jungle Out There", artist: "Randy Newman", movie: "Monk", year: 2002, hint: "Detective with OCD solves crimes." },
    { title: "I Know You Know", artist: "The Friendly Indians", movie: "Psych", year: 2006, hint: "Guy pretends to be psychic detective." },
    { title: "Entourage Theme", artist: "Jane's Addiction", movie: "Entourage", year: 2004, hint: "Movie star brings friends to Hollywood." },
    { title: "Veep Theme", artist: "Rupert Gregson-Williams", movie: "Veep", year: 2012, hint: "Incompetent Vice President seeks power." },
    { title: "Only Murders in the Building", artist: "Siddhartha Khosla", movie: "Only Murders in the Building", year: 2021, hint: "Neighbors podcast about building murder." },
    { title: "The Bear Theme", artist: "Refused", movie: "The Bear", year: 2022, hint: "Fine dining chef runs sandwich shop." },
    { title: "Schitt's Creek Theme", artist: "Maribeth Solomon", movie: "Schitt's Creek", year: 2015, hint: "Rich family forced to live in motel." },
    { title: "Unbreakable Kimmy Schmidt", artist: "The Gregory Brothers", movie: "Unbreakable Kimmy Schmidt", year: 2015, hint: "Cult survivor starts life in NYC." },

    // --- Action/Sci-Fi/Fantasy (Live Action) ---
    { title: "Stranger Things Theme", artist: "Kyle Dixon", movie: "Stranger Things", year: 2016, hint: "Kids fight monsters from Upside Down." },
    { title: "The Mandalorian", artist: "Ludwig Goransson", movie: "The Mandalorian", year: 2019, hint: "Bounty hunter protects green alien infant." },
    { title: "The Witcher Theme", artist: "Sonya Belousova", movie: "The Witcher", year: 2019, hint: "Mutated monster hunter seeks destiny." },
    { title: "Toss A Coin To Your Witcher", artist: "Sonya Belousova", movie: "The Witcher", year: 2019, hint: "Bard sings of white wolf's deeds." },
    { title: "Agatha All Along", artist: "Kristen Anderson-Lopez", movie: "WandaVision", year: 2021, hint: "Neighbor reveals she is a witch." },
    { title: "WandaVision Theme", artist: "Kristen Anderson-Lopez", movie: "WandaVision", year: 2021, hint: "Heroes trap town in sitcom reality." },
    { title: "Loki Theme", artist: "Natalie Holt", movie: "Loki", year: 2021, hint: "God of mischief captured by TVA." },
    { title: "Daredevil Theme", artist: "John Paesano", movie: "Daredevil", year: 2015, hint: "Blind lawyer fights crime at night." },
    { title: "The Boys Theme", artist: "Christopher Lennertz", movie: "The Boys", year: 2019, hint: "Vigilantes fight corrupt corporate superheroes." },
    { title: "Wednesday Main Titles", artist: "Danny Elfman", movie: "Wednesday", year: 2022, hint: "Goth girl investigates school murders." },
    { title: "Sherlock Theme", artist: "David Arnold", movie: "Sherlock", year: 2010, hint: "Modern update of classic detective stories." },
    { title: "Doctor Who Theme", artist: "Murray Gold", movie: "Doctor Who", year: 2005, hint: "Alien travels time in police box." },
    { title: "Ballad of Serenity", artist: "Sonny Rhodes", movie: "Firefly", year: 2002, hint: "Renegade crew on transport ship Serenity." },
    { title: "Battlestar Galactica Theme", artist: "Bear McCreary", movie: "Battlestar Galactica", year: 2004, hint: "Survivors flee Cylon robots in space." },
    { title: "Orphan Black Theme", artist: "Two Fingers", movie: "Orphan Black", year: 2013, hint: "Woman discovers she is a clone." },
    { title: "Black Mirror Theme", artist: "Stuart Earl", movie: "Black Mirror", year: 2011, hint: "Anthology about dark future technology." },
    { title: "Outlander Theme", artist: "Bear McCreary", movie: "Outlander", year: 2014, hint: "WWII nurse time travels to 1743." },

    // --- Drama/Soaps/Teens (Live Action) ---
    { title: "Cosy in the Rocket", artist: "Psapp", movie: "Grey's Anatomy", year: 2005, hint: "Interns become surgeons at Seattle Grace." },
    { title: "Teardrop", artist: "Massive Attack", movie: "House", year: 2004, hint: "Genius diagnostician is addicted to pills." },
    { title: "Desperate Housewives Theme", artist: "Danny Elfman", movie: "Desperate Housewives", year: 2004, hint: "Suburban women hide secrets on Wisteria Lane." },
    { title: "Bad Things", artist: "Jace Everett", movie: "True Blood", year: 2008, hint: "Telepathic waitress meets vampire." },
    { title: "We Used to Be Friends", artist: "The Dandy Warhols", movie: "Veronica Mars", year: 2004, hint: "Teenage private investigator solves crimes." },
    { title: "Secret", artist: "The Pierces", movie: "Pretty Little Liars", year: 2010, hint: "Anonymous figure stalks four friends." },
    { title: "California", artist: "Phantom Planet", movie: "The O.C.", year: 2003, hint: "Troubled teen adopted by wealthy family." },
    { title: "I Don't Want to Be", artist: "Gavin DeGraw", movie: "One Tree Hill", year: 2003, hint: "Half-brothers compete in basketball." },
    { title: "Save Me", artist: "Remy Zero", movie: "Smallville", year: 2001, hint: "Young Superman grows up in Kansas." },
    { title: "Unwritten", artist: "Natasha Bedingfield", movie: "The Hills", year: 2006, hint: "Reality show about young women in LA." },
    { title: "Scandal Theme", artist: "Chad Fischer", movie: "Scandal", year: 2012, hint: "Crisis manager fixes Washington DC scandals." },
    { title: "Bridgerton Theme", artist: "Kris Bowers", movie: "Bridgerton", year: 2020, hint: "Siblings find love in Regency London." },
    { title: "Euphoria Theme", artist: "Labrinth", movie: "Euphoria", year: 2019, hint: "Teens navigate drugs and trauma." },
    { title: "Orange Is the New Black Theme", artist: "Regina Spektor", movie: "Orange Is the New Black", year: 2013, hint: "Woman sentenced to federal prison." },
    { title: "Shameless Theme", artist: "The High Strung", movie: "Shameless", year: 2011, hint: "Drunk father ignores six kids." },
    { title: "Sons of Anarchy Theme", artist: "Curtis Stigers", movie: "Sons of Anarchy", year: 2008, hint: "Outlaw motorcycle club protects town." },
    { title: "Long Hard Times to Come", artist: "Gangstagrass", movie: "Justified", year: 2010, hint: "US Marshal enforces law in Kentucky." },
    { title: "Glee Theme", artist: "Glee Cast", movie: "Glee", year: 2009, hint: "Outcasts join high school show choir." },
    { title: "Empire Theme", artist: "Filthy Rich", movie: "Empire", year: 2015, hint: "Dying hip hop mogul chooses heir." },
    { title: "Friday Night Lights Theme", artist: "Explosions in the Sky", movie: "Friday Night Lights", year: 2006, hint: "Texas town obsessed with football." }
  ],
  classic_tv: [ // Intro themes only. Shows airing BEFORE 2000 (Live Action Only).
    // --- Sitcoms ---
    { title: "I'll Be There for You", artist: "The Rembrandts", movie: "Friends", year: 1994, hint: "Six friends live in NYC apartments." },
    { title: "Seinfeld Theme", artist: "Jonathan Wolff", movie: "Seinfeld", year: 1989, hint: "Comedian and friends analyze minutiae." },
    { title: "Tossed Salads and Scrambled Eggs", artist: "Kelsey Grammer", movie: "Frasier", year: 1993, hint: "Radio shrink lives with dad in Seattle." },
    { title: "Where Everybody Knows Your Name", artist: "Gary Portnoy", movie: "Cheers", year: 1982, hint: "Boston bar where locals gather." },
    { title: "Thank You for Being a Friend", artist: "Cynthia Fee", movie: "The Golden Girls", year: 1985, hint: "Four older women share Miami home." },
    { title: "Everywhere You Look", artist: "Jesse Frederick", movie: "Full House", year: 1987, hint: "Widower raises three daughters with help." },
    { title: "As Days Go By", artist: "Jesse Frederick", movie: "Family Matters", year: 1989, hint: "Winslow family deals with neighbor Urkel." },
    { title: "Saved by the Bell", artist: "Michael Damian", movie: "Saved by the Bell", year: 1989, hint: "High school friends at Bayside." },
    { title: "The Fresh Prince of Bel-Air", artist: "Will Smith", movie: "The Fresh Prince of Bel-Air", year: 1990, hint: "Street smart teen moves to mansion." },
    { title: "Love and Marriage", artist: "Frank Sinatra", movie: "Married... with Children", year: 1987, hint: "Shoe salesman hates his life." },
    { title: "Angela", artist: "Bob James", movie: "Taxi", year: 1978, hint: "Dispatchers and drivers in NYC garage." },
    { title: "Happy Days", artist: "Pratt & McClain", movie: "Happy Days", year: 1974, hint: "The Fonz is cool in 1950s Milwaukee." },
    { title: "Making Our Dreams Come True", artist: "Cyndi Grecco", movie: "Laverne & Shirley", year: 1976, hint: "Two roommates work at brewery." },
    { title: "Come and Knock on Our Door", artist: "Ray Charles", movie: "Three's Company", year: 1977, hint: "Man pretends to be gay for roommate." },
    { title: "It Takes Diff'rent Strokes", artist: "Alan Thicke", movie: "Diff'rent Strokes", year: 1978, hint: "Rich man adopts two Harlem boys." },
    { title: "Movin' On Up", artist: "Ja'net Dubois", movie: "The Jeffersons", year: 1975, hint: "Dry cleaner moves to luxury apartment." },
    { title: "Good Times", artist: "Jim Gilstrap", movie: "Good Times", year: 1974, hint: "Evans family struggles in Chicago projects." },
    { title: "The Streetbeater", artist: "Quincy Jones", movie: "Sanford and Son", year: 1972, hint: "Junk dealer and son in LA." },
    { title: "Those Were the Days", artist: "Carroll O'Connor", movie: "All in the Family", year: 1971, hint: "Bigot argues with liberal son-in-law." },
    { title: "Love is All Around", artist: "Sonny Curtis", movie: "The Mary Tyler Moore Show", year: 1970, hint: "Single woman works in TV news." },
    { title: "The Brady Bunch", artist: "Peppermint Trolley Company", movie: "The Brady Bunch", year: 1969, hint: "Widow and widower merge large families." },
    { title: "The Ballad of Gilligan's Isle", artist: "The Wellingtons", movie: "Gilligan's Island", year: 1964, hint: "Castaways stranded on tropical island." },
    { title: "I Dream of Jeannie", artist: "Hugo Montenegro", movie: "I Dream of Jeannie", year: 1965, hint: "Astronaut finds genie in bottle." },
    { title: "Bewitched", artist: "Howard Greenfield", movie: "Bewitched", year: 1964, hint: "Witch marries mortal advertising exec." },
    { title: "The Addams Family", artist: "Vic Mizzy", movie: "The Addams Family", year: 1964, hint: "Macabre family thinks they are normal." },
    { title: "The Munsters", artist: "Jack Marshall", movie: "The Munsters", year: 1964, hint: "Family of monsters lives in suburbia." },
    { title: "Get Smart Theme", artist: "Irving Szathmary", movie: "Get Smart", year: 1965, hint: "Bumbling spy fights KAOS organization." },
    { title: "Monkees Theme", artist: "The Monkees", movie: "The Monkees", year: 1966, hint: "Four musicians live together in LA." },
    { title: "Come On Get Happy", artist: "The Partridge Family", movie: "The Partridge Family", year: 1970, hint: "Widow and kids form touring band." },
    { title: "MASH Theme", artist: "Johnny Mandel", movie: "M*A*S*H", year: 1972, hint: "Mobile army surgical hospital in Korea." },
    { title: "The Fishin' Hole", artist: "Earle Hagen", movie: "The Andy Griffith Show", year: 1960, hint: "Sheriff without gun in Mayberry." },
    { title: "The Dick Van Dyke Show", artist: "Earle Hagen", movie: "The Dick Van Dyke Show", year: 1961, hint: "Comedy writer balances work and home." },
    { title: "Green Acres", artist: "Vic Mizzy", movie: "Green Acres", year: 1965, hint: "Couple moves from NYC to Hooterville." },
    { title: "The Ballad of Jed Clampett", artist: "Jerry Scoggins", movie: "The Beverly Hillbillies", year: 1962, hint: "Rich hillbillies move to California." },
    { title: "Home Improvement Theme", artist: "Dan Foliart", movie: "Home Improvement", year: 1991, hint: "TV host raises three boys." },
    { title: "Roseanne Theme", artist: "Dan Foliart", movie: "Roseanne", year: 1988, hint: "Working class family in Illinois." },
    { title: "As Long As We Got Each Other", artist: "B.J. Thomas", movie: "Growing Pains", year: 1985, hint: "Psychiatrist dad works from home." },
    { title: "Without Us", artist: "Johnny Mathis", movie: "Family Ties", year: 1982, hint: "Ex-hippies raise conservative son." },
    { title: "Brand New Life", artist: "Steve Wariner", movie: "Who's the Boss?", year: 1984, hint: "Retired baseball player becomes housekeeper." },
    { title: "Murphy Brown Theme", artist: "Steve Dorff", movie: "Murphy Brown", year: 1988, hint: "Recovering alcoholic news anchor." },
    { title: "The Nanny Named Fran", artist: "Ann Hampton Callaway", movie: "The Nanny", year: 1993, hint: "Cosmetics salesgirl becomes posh nanny." },
    { title: "Everybody Loves Raymond", artist: "Rick Marotta", movie: "Everybody Loves Raymond", year: 1996, hint: "Sportswriter deals with nosy parents." },
    { title: "That '70s Show Theme", artist: "Cheap Trick", movie: "That '70s Show", year: 1998, hint: "Teens hang out in Wisconsin basement." },
    { title: "Freaks and Geeks Theme", artist: "Joan Jett", movie: "Freaks and Geeks", year: 1999, hint: "High school burnouts and nerds." },

    // --- Action/Drama/Sci-Fi (Live Action) ---
    { title: "The X-Files", artist: "Mark Snow", movie: "The X-Files", year: 1993, hint: "FBI agents investigate paranormal cases." },
    { title: "Twin Peaks Theme", artist: "Angelo Badalamenti", movie: "Twin Peaks", year: 1990, hint: "FBI agent investigates homecoming queen murder." },
    { title: "Law & Order", artist: "Mike Post", movie: "Law & Order", year: 1990, hint: "Police investigate and DA prosecutes." },
    { title: "Batman Theme", artist: "Neal Hefti", movie: "Batman", year: 1966, hint: "Campy crusader fights colorful villains." },
    { title: "Mission: Impossible", artist: "Lalo Schifrin", movie: "Mission: Impossible", year: 1966, hint: "IMF team executes covert missions." },
    { title: "Hawaii Five-O", artist: "The Ventures", movie: "Hawaii Five-O", year: 1968, hint: "Police unit fights crime in Honolulu." },
    { title: "Theme from Magnum P.I.", artist: "Mike Post", movie: "Magnum, P.I.", year: 1980, hint: "Private eye lives on Hawaii estate." },
    { title: "Miami Vice Theme", artist: "Jan Hammer", movie: "Miami Vice", year: 1984, hint: "Undercover detectives in South Florida." },
    { title: "Knight Rider Theme", artist: "Stu Phillips", movie: "Knight Rider", year: 1982, hint: "Man fights crime with talking car." },
    { title: "The A-Team Theme", artist: "Mike Post", movie: "The A-Team", year: 1983, hint: "Mercenaries help people in trouble." },
    { title: "MacGyver Theme", artist: "Randy Edelman", movie: "MacGyver", year: 1985, hint: "Agent improvises tools from junk." },
    { title: "Good Ol' Boys", artist: "Waylon Jennings", movie: "The Dukes of Hazzard", year: 1979, hint: "Cousins outrun corrupt county commissioner." },
    { title: "With a Little Help From My Friends", artist: "Joe Cocker", movie: "The Wonder Years", year: 1988, hint: "Adult narrates his suburban childhood." },
    { title: "I'm Always Here", artist: "Jimi Jamison", movie: "Baywatch", year: 1989, hint: "Lifeguards patrol LA beaches." },
    { title: "Bad Boys", artist: "Inner Circle", movie: "Cops", year: 1989, hint: "Reality show follows police officers." },
    { title: "Star Trek Theme", artist: "Alexander Courage", movie: "Star Trek", year: 1966, hint: "Five year mission to explore space." },
    { title: "Star Trek: TNG Theme", artist: "Jerry Goldsmith", movie: "Star Trek: The Next Generation", year: 1987, hint: "Picard leads Enterprise D crew." },
    { title: "Star Trek: DS9 Theme", artist: "Dennis McCarthy", movie: "Star Trek: Deep Space Nine", year: 1993, hint: "Commander Sisko runs space station." },
    { title: "Star Trek: Voyager Theme", artist: "Jerry Goldsmith", movie: "Star Trek: Voyager", year: 1995, hint: "Starship stranded 70,000 lightyears away." },
    { title: "The Twilight Zone", artist: "Marius Constant", movie: "The Twilight Zone", year: 1959, hint: "Anthology of sci-fi and horror tales." },
    { title: "Alfred Hitchcock Presents", artist: "Charles Gounod", movie: "Alfred Hitchcock Presents", year: 1955, hint: "Director introduces suspenseful anthology stories." },
    { title: "Perry Mason Theme", artist: "Fred Steiner", movie: "Perry Mason", year: 1957, hint: "Defense attorney clears innocent clients." },
    { title: "Bonanza Theme", artist: "Jay Livingston", movie: "Bonanza", year: 1959, hint: "Father and sons run Ponderosa ranch." },
    { title: "Rawhide", artist: "Frankie Laine", movie: "Rawhide", year: 1959, hint: "Drovers move cattle across west." },
    { title: "Dallas Theme", artist: "Jerrold Immel", movie: "Dallas", year: 1978, hint: "Wealthy oil family feuds in Texas." },
    { title: "Dynasty Theme", artist: "Bill Conti", movie: "Dynasty", year: 1981, hint: "Oil tycoons clash in Denver." },
    { title: "Hill Street Blues Theme", artist: "Mike Post", movie: "Hill Street Blues", year: 1981, hint: "Police station deals with urban crime." },
    { title: "St. Elsewhere Theme", artist: "Dave Grusin", movie: "St. Elsewhere", year: 1982, hint: "Doctors at decaying Boston hospital." },
    { title: "L.A. Law Theme", artist: "Mike Post", movie: "L.A. Law", year: 1986, hint: "High priced lawyers in Los Angeles." },
    { title: "NYPD Blue Theme", artist: "Mike Post", movie: "NYPD Blue", year: 1993, hint: "Detectives work at 15th precinct." },
    { title: "ER Theme", artist: "James Newton Howard", movie: "ER", year: 1994, hint: "Doctors save lives in Chicago hospital." },
    { title: "The West Wing Theme", artist: "W.G. Snuffy Walden", movie: "The West Wing", year: 1999, hint: "President Bartlet runs the country." },
    { title: "Buffy the Vampire Slayer Theme", artist: "Nerf Herder", movie: "Buffy the Vampire Slayer", year: 1997, hint: "Chosen girl fights demons in high school." },
    { title: "How Soon Is Now?", artist: "Love Spit Love", movie: "Charmed", year: 1998, hint: "Three sisters discover they are witches." },
    { title: "Dawson's Creek Theme", artist: "Paula Cole", movie: "Dawson's Creek", year: 1998, hint: "Friends grow up in Capeside." },
    { title: "I Don't Want to Wait", artist: "Paula Cole", movie: "Dawson's Creek", year: 1998, hint: "Teen filmmaker loves girl next door." },
    { title: "Searchin' My Soul", artist: "Vonda Shepard", movie: "Ally McBeal", year: 1997, hint: "Neurotic lawyer hallucinates dancing baby." },
    { title: "Closer to Free", artist: "BoDeans", movie: "Party of Five", year: 1994, hint: "Five siblings raise each other." },
    { title: "Beverly Hills 90210", artist: "John E. Davis", movie: "Beverly Hills, 90210", year: 1990, hint: "Minnesota twins move to fancy zip code." },
    { title: "Melrose Place Theme", artist: "Tim Truman", movie: "Melrose Place", year: 1992, hint: "Scandals at West Hollywood apartment complex." },
    { title: "Believe It or Not", artist: "Joey Scarbury", movie: "The Greatest American Hero", year: 1981, hint: "Teacher gets alien super suit." },
    { title: "Moonlighting", artist: "Al Jarreau", movie: "Moonlighting", year: 1985, hint: "Model and detective run agency." },
    { title: "Airwolf Theme", artist: "Sylvester Levay", movie: "Airwolf", year: 1984, hint: "Pilot flies supersonic military helicopter." },
    { title: "Peter Gunn", artist: "Henry Mancini", movie: "Peter Gunn", year: 1958, hint: "Private investigator frequents jazz club." },
    { title: "Dragnet Theme", artist: "Walter Schumann", movie: "Dragnet", year: 1951, hint: "Sgt Friday asks for just facts." },
    { title: "The Love Boat", artist: "Jack Jones", movie: "The Love Boat", year: 1977, hint: "Passengers find romance on cruise." },
    { title: "Fantasy Island", artist: "Laurence Rosenthal", movie: "Fantasy Island", year: 1977, hint: "Guests fulfill wishes at resort." },
    { title: "Charlie's Angels Theme", artist: "Jack Elliott", movie: "Charlie's Angels", year: 1976, hint: "Three women work for mysterious voice." },
    { title: "Wonder Woman", artist: "Charles Fox", movie: "Wonder Woman", year: 1975, hint: "Amazon princess fights Nazis and crime." },
    { title: "The Incredible Hulk", artist: "Joe Harnell", movie: "The Incredible Hulk", year: 1978, hint: "Scientist turns green when angry." },
    { title: "Murder, She Wrote", artist: "John Addison", movie: "Murder, She Wrote", year: 1984, hint: "Mystery writer solves real murders." },
    { title: "Matlock Theme", artist: "Dick DeBenedictis", movie: "Matlock", year: 1986, hint: "Folksy lawyer wins expensive cases." },
    { title: "Walker, Texas Ranger", artist: "Chuck Norris", movie: "Walker, Texas Ranger", year: 1993, hint: "Martial artist ranger fights crime." },
    { title: "Unsolved Mysteries", artist: "Gary Malkin", movie: "Unsolved Mysteries", year: 1987, hint: "Show asks public to solve crimes." },
    { title: "Reading Rainbow", artist: "Tina Fabrique", movie: "Reading Rainbow", year: 1983, hint: "LeVar Burton encourages kids reading." },
    { title: "Mister Rogers' Neighborhood", artist: "Fred Rogers", movie: "Mister Rogers' Neighborhood", year: 1968, hint: "Host teaches kindness with puppets." },
    { title: "Sesame Street Theme", artist: "The Kids", movie: "Sesame Street", year: 1969, hint: "Muppets and humans live on street." },
    { title: "The Muppet Show Theme", artist: "The Muppets", movie: "The Muppet Show", year: 1976, hint: "Frog manages chaotic variety show." },
    { title: "Fraggle Rock Theme", artist: "The Fraggles", movie: "Fraggle Rock", year: 1983, hint: "Underground creatures love to sing." }
  ],
  movie_soundtracks: [ // Live-action movie songs (Vocals allowed).
    { title: "My Heart Will Go On", artist: "Celine Dion", movie: "Titanic", year: 1997, hint: "Jack and Rose on a sinking ship." },
    { title: "I Will Always Love You", artist: "Whitney Houston", movie: "The Bodyguard", year: 1992, hint: "Agent protects pop star from stalker." },
    { title: "Eye of the Tiger", artist: "Survivor", movie: "Rocky III", year: 1982, hint: "Balboa trains to fight Clubber Lang." },
    { title: "Lose Yourself", artist: "Eminem", movie: "8 Mile", year: 2002, hint: "Aspiring rapper struggles in Detroit." },
    { title: "Shallow", artist: "Lady Gaga & Bradley Cooper", movie: "A Star Is Born", year: 2018, hint: "Fading star helps young singer." },
    { title: "Skyfall", artist: "Adele", movie: "Skyfall", year: 2012, hint: "Bond defends his childhood home." },
    { title: "Danger Zone", artist: "Kenny Loggins", movie: "Top Gun", year: 1986, hint: "Maverick flies F-14s." },
    { title: "Take My Breath Away", artist: "Berlin", movie: "Top Gun", year: 1986, hint: "Maverick romances Charlie." },
    { title: "Footloose", artist: "Kenny Loggins", movie: "Footloose", year: 1984, hint: "City boy overturns town dancing ban." },
    { title: "Ghostbusters", artist: "Ray Parker Jr.", movie: "Ghostbusters", year: 1984, hint: "Scientists start paranormal elimination service." },
    { title: "Stayin' Alive", artist: "Bee Gees", movie: "Saturday Night Fever", year: 1977, hint: "Brooklyn paint store clerk loves disco." },
    { title: "Unchained Melody", artist: "The Righteous Brothers", movie: "Ghost", year: 1990, hint: "Murdered banker tries to warn girlfriend." },
    { title: "(I've Had) The Time of My Life", artist: "Bill Medley & Jennifer Warnes", movie: "Dirty Dancing", year: 1987, hint: "Girl falls for dance instructor at resort." },
    { title: "Don't You (Forget About Me)", artist: "Simple Minds", movie: "The Breakfast Club", year: 1985, hint: "Five students in Saturday detention." },
    { title: "Mrs. Robinson", artist: "Simon & Garfunkel", movie: "The Graduate", year: 1967, hint: "Graduate seduced by father's partner's wife." },
    { title: "Streets of Philadelphia", artist: "Bruce Springsteen", movie: "Philadelphia", year: 1993, hint: "Lawyer sues firm for AIDS discrimination." },
    { title: "Purple Rain", artist: "Prince", movie: "Purple Rain", year: 1984, hint: "Musician deals with abusive father." },
    { title: "9 to 5", artist: "Dolly Parton", movie: "9 to 5", year: 1980, hint: "Three women kidnap their sexist boss." },
    { title: "Fame", artist: "Irene Cara", movie: "Fame", year: 1980, hint: "Students attend NYC performing arts school." },
    { title: "Flashdance... What a Feeling", artist: "Irene Cara", movie: "Flashdance", year: 1983, hint: "Welder wants to be a ballerina." },
    { title: "Gangsta's Paradise", artist: "Coolio", movie: "Dangerous Minds", year: 1995, hint: "Marine teaches tough inner city kids." },
    { title: "Kiss from a Rose", artist: "Seal", movie: "Batman Forever", year: 1995, hint: "Two-Face and Riddler threaten Gotham." },
    { title: "Men in Black", artist: "Will Smith", movie: "Men in Black", year: 1997, hint: "Agents monitor extraterrestrials on Earth." },
    { title: "See You Again", artist: "Wiz Khalifa ft. Charlie Puth", movie: "Furious 7", year: 2015, hint: "Tribute to Paul Walker." },
    { title: "Moon River", artist: "Audrey Hepburn", movie: "Breakfast at Tiffany's", year: 1961, hint: "Socialite searches for rich husband." },
    { title: "Over the Rainbow", artist: "Judy Garland", movie: "The Wizard of Oz", year: 1939, hint: "Tornado takes girl to Oz." },
    { title: "Singin' in the Rain", artist: "Gene Kelly", movie: "Singin' in the Rain", year: 1952, hint: "Silent film stars transition to talkies." },
    { title: "As Time Goes By", artist: "Dooley Wilson", movie: "Casablanca", year: 1942, hint: "Cafe owner reunites with old flame." },
    { title: "Goldfinger", artist: "Shirley Bassey", movie: "Goldfinger", year: 1964, hint: "Villain plans to irradiate Fort Knox." },
    { title: "Live and Let Die", artist: "Paul McCartney & Wings", movie: "Live and Let Die", year: 1973, hint: "Bond investigates Harlem drug lord." },
    { title: "Nobody Does It Better", artist: "Carly Simon", movie: "The Spy Who Loved Me", year: 1977, hint: "Bond teams with Russian agent." },
    { title: "For Your Eyes Only", artist: "Sheena Easton", movie: "For Your Eyes Only", year: 1981, hint: "Bond retrieves ATAC system." },
    { title: "A View to a Kill", artist: "Duran Duran", movie: "A View to a Kill", year: 1985, hint: "Villain plans to destroy Silicon Valley." },
    { title: "Old Time Rock and Roll", artist: "Bob Seger", movie: "Risky Business", year: 1983, hint: "Teen runs brothel in parents' house." },
    { title: "Twist and Shout", artist: "The Beatles", movie: "Ferris Bueller's Day Off", year: 1986, hint: "High schooler fakes sick day." },
    { title: "In Your Eyes", artist: "Peter Gabriel", movie: "Say Anything...", year: 1989, hint: "Underachiever woos valedictorian." },
    { title: "Born to be Wild", artist: "Steppenwolf", movie: "Easy Rider", year: 1969, hint: "Bikers travel from LA to New Orleans." },
    { title: "The Sound of Silence", artist: "Simon & Garfunkel", movie: "The Graduate", year: 1967, hint: "Graduate has affair with Mrs. Robinson." },
    { title: "Knockin' on Heaven's Door", artist: "Bob Dylan", movie: "Pat Garrett & Billy the Kid", year: 1973, hint: "Lawman hunts down his old friend." },
    { title: "Fight the Power", artist: "Public Enemy", movie: "Do the Right Thing", year: 1989, hint: "Tension rises on hot Brooklyn day." },
    { title: "Save Me", artist: "Aimee Mann", movie: "Magnolia", year: 1999, hint: "Interconnected lives in San Fernando Valley." },
    { title: "Falling Slowly", artist: "Glen Hansard & Markéta Irglová", movie: "Once", year: 2007, hint: "Street musician meets flower seller." },
    { title: "Into the West", artist: "Annie Lennox", movie: "The Lord of the Rings: The Return of the King", year: 2003, hint: "Ring destroyed in Mount Doom." },
    { title: "Jai Ho", artist: "A.R. Rahman", movie: "Slumdog Millionaire", year: 2008, hint: "Orphan answers trivia for millions." },
    { title: "Happy", artist: "Pharrell Williams", movie: "Despicable Me 2", year: 2013, hint: "Villain turned dad recruited by league." },
    { title: "No Time To Die", artist: "Billie Eilish", movie: "No Time To Die", year: 2021, hint: "Bond faces villain with nanobots." },
    { title: "Writing's on the Wall", artist: "Sam Smith", movie: "Spectre", year: 2015, hint: "Bond discovers Blofeld is his brother." },
    { title: "City of Stars", artist: "Ryan Gosling & Emma Stone", movie: "La La Land", year: 2016, hint: "Actress and pianist romance in LA." },
    { title: "Young and Beautiful", artist: "Lana Del Rey", movie: "The Great Gatsby", year: 2013, hint: "Millionaire throws parties for lost love." },
    { title: "Love Me Like You Do", artist: "Ellie Goulding", movie: "Fifty Shades of Grey", year: 2015, hint: "Student interviews wealthy businessman." },
    // --- New Additions ---
    { title: "I Don't Want to Miss a Thing", artist: "Aerosmith", movie: "Armageddon", year: 1998, hint: "Drillers go to space to stop asteroid." },
    { title: "My Sharona", artist: "The Knack", movie: "Reality Bites", year: 1994, hint: "Gen X friends struggle after college." },
    { title: "Regulate", artist: "Warren G", movie: "Above the Rim", year: 1994, hint: "High school basketball star faces gangs." },
    { title: "Iris", artist: "Goo Goo Dolls", movie: "City of Angels", year: 1998, hint: "Angel falls in love with doctor." },
    { title: "Uninvited", artist: "Alanis Morissette", movie: "City of Angels", year: 1998, hint: "Cage gives up immortality for love." },
    { title: "Earned It", artist: "The Weeknd", movie: "Fifty Shades of Grey", year: 2015, hint: "Relationship involves a contract." },
    { title: "The Power of Love", artist: "Huey Lewis and the News", movie: "Back to the Future", year: 1985, hint: "Doc Brown invents time travel." },
    { title: "(Everything I Do) I Do It for You", artist: "Bryan Adams", movie: "Robin Hood: Prince of Thieves", year: 1991, hint: "Thief steals from rich for poor." },
    { title: "Kiss Me", artist: "Sixpence None the Richer", movie: "She's All That", year: 1999, hint: "Jock bets he can makeover nerd." },
    { title: "Bohemian Rhapsody", artist: "Queen", movie: "Wayne's World", year: 1992, hint: "Two slackers host public access show." },
    { title: "Tiny Dancer", artist: "Elton John", movie: "Almost Famous", year: 2000, hint: "Teen writes for Rolling Stone magazine." },
    { title: "Stuck in the Middle with You", artist: "Stealers Wheel", movie: "Reservoir Dogs", year: 1992, hint: "Jewel heist goes wrong." },
    { title: "You Never Can Tell", artist: "Chuck Berry", movie: "Pulp Fiction", year: 1994, hint: "Mob hitmen and boxer stories intertwine." },
    { title: "Girl, You'll Be a Woman Soon", artist: "Urge Overkill", movie: "Pulp Fiction", year: 1994, hint: "Vincent Vega takes boss's wife out." },
    { title: "Lust for Life", artist: "Iggy Pop", movie: "Trainspotting", year: 1996, hint: "Edinburgh heroin addicts try to cope." },
    { title: "Born Slippy .NUXX", artist: "Underworld", movie: "Trainspotting", year: 1996, hint: "Friends sell drugs in London." },
    { title: "Where Is My Mind?", artist: "Pixies", movie: "Fight Club", year: 1999, hint: "Man creates underground fighting ring." },
    { title: "Theme from Shaft", artist: "Isaac Hayes", movie: "Shaft", year: 1971, hint: "Black private dick battles mob." },
    { title: "Superfly", artist: "Curtis Mayfield", movie: "Superfly", year: 1972, hint: "Cocaine dealer tries to quit business." },
    { title: "Across 110th Street", artist: "Bobby Womack", movie: "Jackie Brown", year: 1997, hint: "Flight attendant smuggles money." },
    { title: "Raindrops Keep Fallin' on My Head", artist: "B.J. Thomas", movie: "Butch Cassidy and the Sundance Kid", year: 1969, hint: "Outlaws flee to Bolivia." },
    { title: "Everybody's Talkin'", artist: "Harry Nilsson", movie: "Midnight Cowboy", year: 1969, hint: "Texan dishwasher becomes gigolo in NYC." },
    { title: "It Must Have Been Love", artist: "Roxette", movie: "Pretty Woman", year: 1990, hint: "Businessman hires escort for week." },
    { title: "King of Wishful Thinking", artist: "Go West", movie: "Pretty Woman", year: 1990, hint: "Julia Roberts plays Cinderella hooker." },
    { title: "Maniac", artist: "Michael Sembello", movie: "Flashdance", year: 1983, hint: "Steel mill worker dances at night." },
    { title: "Up Where We Belong", artist: "Joe Cocker & Jennifer Warnes", movie: "An Officer and a Gentleman", year: 1982, hint: "Navy aviation candidate fights drill sergeant." },
    { title: "Against All Odds (Take a Look at Me Now)", artist: "Phil Collins", movie: "Against All Odds", year: 1984, hint: "Football player searches for girlfriend." },
    { title: "Glory of Love", artist: "Peter Cetera", movie: "The Karate Kid Part II", year: 1986, hint: "Miyagi and Daniel travel to Japan." },
    { title: "You're the Best", artist: "Joe Esposito", movie: "The Karate Kid", year: 1984, hint: "Teen learns karate to fight bullies." },
    { title: "Burning Heart", artist: "Survivor", movie: "Rocky IV", year: 1985, hint: "Rocky fights Russian Drago." },
    { title: "New York, New York", artist: "Liza Minnelli", movie: "New York, New York", year: 1977, hint: "Musician and singer romance in NYC." },
    { title: "All That Jazz", artist: "Chita Rivera", movie: "Chicago", year: 2002, hint: "Murderesses vie for fame." },
    { title: "Diamonds Are a Girl's Best Friend", artist: "Marilyn Monroe", movie: "Gentlemen Prefer Blondes", year: 1953, hint: "Showgirls seek rich husbands in Paris." },
    { title: "Supercalifragilisticexpialidocious", artist: "Julie Andrews", movie: "Mary Poppins", year: 1964, hint: "Magical nanny arrives via umbrella." },
    { title: "A Spoonful of Sugar", artist: "Julie Andrews", movie: "Mary Poppins", year: 1964, hint: "Banks children get a magical nanny." },
    { title: "Chim Chim Cher-ee", artist: "Dick Van Dyke", movie: "Mary Poppins", year: 1964, hint: "Nanny and sweep jump into pictures." },
    { title: "When Doves Cry", artist: "Prince", movie: "Purple Rain", year: 1984, hint: "The Kid navigates Minneapolis music scene." },
    { title: "On the Road Again", artist: "Willie Nelson", movie: "Honeysuckle Rose", year: 1980, hint: "Country singer struggles with family life." },
    { title: "Rainbow Connection", artist: "Kermit the Frog", movie: "The Muppet Movie", year: 1979, hint: "Frog travels to Hollywood for stardom." },
    { title: "Pure Imagination", artist: "Gene Wilder", movie: "Willy Wonka & the Chocolate Factory", year: 1971, hint: "Golden ticket winners tour candy factory." },
    { title: "The Candy Man", artist: "Aubrey Woods", movie: "Willy Wonka & the Chocolate Factory", year: 1971, hint: "Poor boy finds a golden ticket." },
    { title: "Ding-Dong! The Witch Is Dead", artist: "The Munchkins", movie: "The Wizard of Oz", year: 1939, hint: "Kansas girl travels to Emerald City." },
    { title: "If I Only Had a Brain", artist: "Ray Bolger", movie: "The Wizard of Oz", year: 1939, hint: "Travelers seek heart, brain, and courage." },
    { title: "We're Off to See the Wizard", artist: "Judy Garland", movie: "The Wizard of Oz", year: 1939, hint: "Kansas girl follows the yellow brick road." },
    { title: "Grease", artist: "Frankie Valli", movie: "Grease", year: 1978, hint: "Danny and Sandy fall in love." },
    { title: "You're the One That I Want", artist: "John Travolta & Olivia Newton-John", movie: "Grease", year: 1978, hint: "50s high school romance and cars." },
    { title: "Summer Nights", artist: "John Travolta & Olivia Newton-John", movie: "Grease", year: 1978, hint: "Summer romance at Rydell High School." },
    { title: "Hopelessly Devoted to You", artist: "Olivia Newton-John", movie: "Grease", year: 1978, hint: "Good girl loves a bad boy." },
    { title: "Greased Lightnin'", artist: "John Travolta", movie: "Grease", year: 1978, hint: "T-Birds build a hot rod car." },
    { title: "Beauty School Dropout", artist: "Frankie Avalon", movie: "Grease", year: 1978, hint: "Rydell High students sing and dance." },
    { title: "Sound of Music", artist: "Julie Andrews", movie: "The Sound of Music", year: 1965, hint: "Governess cares for seven Austrian children." },
    { title: "My Favorite Things", artist: "Julie Andrews", movie: "The Sound of Music", year: 1965, hint: "Captain Von Trapp needs a nanny." },
    { title: "Do-Re-Mi", artist: "Julie Andrews", movie: "The Sound of Music", year: 1965, hint: "Nun leaves convent to govern children." },
    { title: "Edelweiss", artist: "Christopher Plummer", movie: "The Sound of Music", year: 1965, hint: "Family escapes Nazis over the Alps." },
    { title: "Tomorrow", artist: "Aileen Quinn", movie: "Annie", year: 1982, hint: "Billionaire Warbucks adopts a redhead orphan." },
    { title: "It's the Hard-Knock Life", artist: "Aileen Quinn", movie: "Annie", year: 1982, hint: "Miss Hannigan runs a terrible orphanage." },
    { title: "Time Warp", artist: "Richard O'Brien", movie: "The Rocky Horror Picture Show", year: 1975, hint: "Couple stranded at a strange castle." },
    { title: "Sweet Transvestite", artist: "Tim Curry", movie: "The Rocky Horror Picture Show", year: 1975, hint: "Alien scientist builds a muscle man." },
    { title: "Science Fiction/Double Feature", artist: "Richard O'Brien", movie: "The Rocky Horror Picture Show", year: 1975, hint: "Brad and Janet meet Dr. Frank-N-Furter." }
  ],
  cartoons: [ // All animated TV shows (Modern & Classic).
    { title: "The Simpsons Theme", artist: "Danny Elfman", movie: "The Simpsons", year: 1989, hint: "Yellow family lives in Springfield." },
    { title: "Meet the Flintstones", artist: "Hoyt Curtin", movie: "The Flintstones", year: 1960, hint: "Stone age family uses dinosaur appliances." },
    { title: "The Jetsons", artist: "Hoyt Curtin", movie: "The Jetsons", year: 1962, hint: "Space age family with robot maid." },
    { title: "Scooby-Doo, Where Are You!", artist: "Larry Marks", movie: "Scooby-Doo", year: 1969, hint: "Teens and dog solve spooky mysteries." },
    { title: "DuckTales Theme", artist: "Jeff Pescetto", movie: "DuckTales", year: 1987, hint: "Rich duck goes on adventures with nephews." },
    { title: "Teenage Mutant Ninja Turtles", artist: "Chuck Lorre", movie: "Teenage Mutant Ninja Turtles", year: 1987, hint: "Reptiles trained by rat fight Shredder." },
    { title: "Pokémon Theme", artist: "Jason Paige", movie: "Pokémon", year: 1998, hint: "Kids catch monsters in balls." },
    { title: "Go Go Power Rangers", artist: "Ron Wasserman", movie: "Mighty Morphin Power Rangers", year: 1993, hint: "Teens fight Rita Repulsa with Zords." },
    { title: "X-Men: The Animated Series", artist: "Ron Wasserman", movie: "X-Men", year: 1992, hint: "Mutant school fights for equality." },
    { title: "Batman: The Animated Series", artist: "Danny Elfman", movie: "Batman: The Animated Series", year: 1992, hint: "Caped crusader protects Gotham City." },
    { title: "Inspector Gadget", artist: "Shuki Levy", movie: "Inspector Gadget", year: 1983, hint: "Cyborg detective battles Dr. Claw." },
    { title: "ThunderCats", artist: "Bernard Hoffer", movie: "ThunderCats", year: 1985, hint: "Cat-like aliens fight Mumm-Ra." },
    { title: "Transformers", artist: "Anne Bryant", movie: "The Transformers", year: 1984, hint: "Autobots battle Decepticons on Earth." },
    { title: "G.I. Joe", artist: "Ford Kinder", movie: "G.I. Joe: A Real American Hero", year: 1983, hint: "Soldiers fight Cobra terrorist organization." },
    { title: "Captain Planet", artist: "Tom Worrall", movie: "Captain Planet", year: 1990, hint: "Blue superhero fights pollution." },
    { title: "Animaniacs", artist: "Rob Paulsen", movie: "Animaniacs", year: 1993, hint: "Warner siblings cause chaos on lot." },
    { title: "BoJack Horseman Theme", artist: "Patrick Carney", movie: "BoJack Horseman", year: 2014, hint: "Washed up sitcom horse navigates depression." },
    { title: "Rick and Morty Theme", artist: "Ryan Elder", movie: "Rick and Morty", year: 2013, hint: "Drunken scientist travels dimensions with grandson." },
    { title: "Bob's Burgers Theme", artist: "Loren Bouchard", movie: "Bob's Burgers", year: 2011, hint: "Family runs struggling burger restaurant." },
    { title: "Archer Theme", artist: "Scott Sims", movie: "Archer", year: 2009, hint: "Spy agency deals with office politics." },
    { title: "Adventure Time", artist: "Pendleton Ward", movie: "Adventure Time", year: 2010, hint: "Boy and magic dog fight Ice King." },
    { title: "Family Guy Theme", artist: "Walter Murphy", movie: "Family Guy", year: 1999, hint: "Rhode Island family with talking dog." },
    { title: "Futurama Theme", artist: "Christopher Tyng", movie: "Futurama", year: 1999, hint: "Pizza boy frozen for 1000 years." },
    { title: "SpongeBob SquarePants Theme", artist: "Patrick Pinney", movie: "SpongeBob SquarePants", year: 1999, hint: "Sea sponge works at Krusty Krab." },
    { title: "King of the Hill Theme", artist: "The Refreshments", movie: "King of the Hill", year: 1997, hint: "Texas man loves propane and accessories." },
    { title: "South Park Theme", artist: "Primus", movie: "South Park", year: 1997, hint: "Four foul-mouthed boys in Colorado." },
    { title: "Arcane Theme", artist: "Imagine Dragons", movie: "Arcane", year: 2021, hint: "Sisters on opposite sides of war." },
    { title: "Invincible Theme", artist: "John Paesano", movie: "Invincible", year: 2021, hint: "Son of superhero discovers dark secret." },
    { title: "Avatar: The Last Airbender", artist: "Jeremy Zuckerman", movie: "Avatar: The Last Airbender", year: 2005, hint: "Boy frozen in ice saves world." },
    // --- New Cartoon Additions ---
    { title: "Gravity Falls Theme", artist: "Brad Breeck", movie: "Gravity Falls", year: 2012, hint: "Twins spend summer with great uncle." },
    { title: "Phineas and Ferb Theme", artist: "Bowling for Soup", movie: "Phineas and Ferb", year: 2007, hint: "Brothers build inventions during summer." },
    { title: "Fairly OddParents Theme", artist: "Ron Jones", movie: "The Fairly OddParents", year: 2001, hint: "Boy gets wishes from magic couple." },
    { title: "Call Me, Beep Me", artist: "Christina Milian", movie: "Kim Possible", year: 2002, hint: "Teen hero fights Dr. Drakken." },
    { title: "Danny Phantom Theme", artist: "Guy Moon", movie: "Danny Phantom", year: 2004, hint: "Boy fights ghosts with ghost powers." },
    { title: "The Powerpuff Girls Theme", artist: "James L. Venable", movie: "The Powerpuff Girls", year: 1998, hint: "Three superpowered girls created in lab." },
    { title: "Dexter's Laboratory Theme", artist: "Thomas Chase", movie: "Dexter's Laboratory", year: 1996, hint: "Boy genius hides lab from sister." },
    { title: "Johnny Bravo Theme", artist: "Louis Fagenson", movie: "Johnny Bravo", year: 1997, hint: "Muscular man fails to get dates." },
    { title: "Courage the Cowardly Dog Theme", artist: "Jody Gray", movie: "Courage the Cowardly Dog", year: 1999, hint: "Scared dog protects owners in Nowhere." },
    { title: "Ed, Edd n Eddy Theme", artist: "Patric Caird", movie: "Ed, Edd n Eddy", year: 1999, hint: "Three boys named Ed scam cul-de-sac." },
    { title: "Samurai Jack Theme", artist: "will.i.am", movie: "Samurai Jack", year: 2001, hint: "Warrior fights shapeshifting master of darkness." },
    { title: "Teen Titans Theme", artist: "Puffy AmiYumi", movie: "Teen Titans", year: 2003, hint: "Teenage sidekicks form their own team." },
    { title: "Rugrats Theme", artist: "Mark Mothersbaugh", movie: "Rugrats", year: 1991, hint: "Adventures seen from baby's perspective." },
    { title: "Hey Arnold! Theme", artist: "Jim Lang", movie: "Hey Arnold!", year: 1996, hint: "City kid lives in boarding house." },
    { title: "Wild Thornberrys Theme", artist: "Drew Neumann", movie: "The Wild Thornberrys", year: 1998, hint: "Girl talks to animals on safari." },
    { title: "CatDog Theme", artist: "Peter Hannan", movie: "CatDog", year: 1998, hint: "Conjoined siblings are different species." },
    { title: "Ren & Stimpy Theme", artist: "Die Screamende Lippenchees", movie: "The Ren & Stimpy Show", year: 1991, hint: "Crazy chihuahua and dumb cat." },
    { title: "Rocko's Modern Life Theme", artist: "The B-52's", movie: "Rocko's Modern Life", year: 1993, hint: "Wallaby navigates modern American life." },
    { title: "Pinky and the Brain Theme", artist: "Richard Stone", movie: "Pinky and the Brain", year: 1995, hint: "Lab mice plot world domination." },
    { title: "Tiny Toon Adventures Theme", artist: "Bruce Broughton", movie: "Tiny Toon Adventures", year: 1990, hint: "Young toons learn from classic characters." },
    { title: "Batman Beyond Theme", artist: "Kristopher Carter", movie: "Batman Beyond", year: 1999, hint: "Teen takes mantle of Batman in future." },
    { title: "Justice League Theme", artist: "Lolita Ritmanis", movie: "Justice League", year: 2001, hint: "World's greatest heroes form team." },
    { title: "Superman: The Animated Series Theme", artist: "Shirley Walker", movie: "Superman: The Animated Series", year: 1996, hint: "Clark Kent fights Lex Luthor." },
    { title: "Spider-Man Theme", artist: "Paul Francis Webster", movie: "Spider-Man", year: 1967, hint: "Teen bitten by radioactive spider." },
    { title: "Spider-Man: The Animated Series Theme", artist: "Joe Perry", movie: "Spider-Man: The Animated Series", year: 1994, hint: "Peter Parker balances life and heroics." },
    { title: "He-Man and the Masters of the Universe Theme", artist: "Shuki Levy", movie: "He-Man and the Masters of the Universe", year: 1983, hint: "Prince Adam defends Castle Grayskull." },
    { title: "She-Ra: Princess of Power Theme", artist: "Shuki Levy", movie: "She-Ra: Princess of Power", year: 1985, hint: "Adora fights the Evil Horde." },
    { title: "Jem and the Holograms Theme", artist: "Kinder & Bryant", movie: "Jem", year: 1985, hint: "Music executive has secret rock persona." },
    { title: "My Little Pony: Friendship Is Magic Theme", artist: "Daniel Ingram", movie: "My Little Pony: Friendship Is Magic", year: 2010, hint: "Ponies learn lessons in Equestria." },
    // --- Anime Hits ---
    { title: "A Cruel Angel's Thesis", artist: "Yoko Takahashi", movie: "Neon Genesis Evangelion", year: 1995, hint: "Teens pilot mechs against Angels." },
    { title: "Tank!", artist: "The Seatbelts", movie: "Cowboy Bebop", year: 1998, hint: "Space bounty hunters on the Bebop." },
    { title: "Cha-La Head-Cha-La", artist: "Hironobu Kageyama", movie: "Dragon Ball Z", year: 1989, hint: "Goku defends Earth from aliens." },
    { title: "Rock the Dragon", artist: "Jeremy Sweet", movie: "Dragon Ball Z", year: 1996, hint: "Z Fighters battle powerful foes." },
    { title: "We Are!", artist: "Hiroshi Kitadani", movie: "One Piece", year: 1999, hint: "Rubber boy seeks ultimate treasure." },
    { title: "Moonlight Densetsu", artist: "DALI", movie: "Sailor Moon", year: 1992, hint: "Schoolgirl transforms into lunar guardian." },
    { title: "Blue Bird", artist: "Ikimonogakari", movie: "Naruto Shippuden", year: 2008, hint: "Ninja seeks to become Hokage." },
    { title: "Guren no Yumiya", artist: "Linked Horizon", movie: "Attack on Titan", year: 2013, hint: "Humanity lives behind walls." },
    { title: "The World", artist: "Nightmare", movie: "Death Note", year: 2006, hint: "Student kills criminals with notebook." },
    { title: "Unravel", artist: "TK from Ling Tosite Sigure", movie: "Tokyo Ghoul", year: 2014, hint: "Boy becomes half-ghoul after date." },
    { title: "Gurenge", artist: "LiSA", movie: "Demon Slayer", year: 2019, hint: "Boy hunts demons to cure sister." },
    { title: "Kick Back", artist: "Kenshi Yonezu", movie: "Chainsaw Man", year: 2022, hint: "Man merges with chainsaw devil." }
  ],
  musicals: [
    { title: "Alexander Hamilton", artist: "Leslie Odom Jr.", movie: "Hamilton", year: 2020, hint: "Founding Father's life told through rap." },
    { title: "My Shot", artist: "Lin-Manuel Miranda", movie: "Hamilton", year: 2020, hint: "Rebels gather to plan revolution." },
    { title: "The Room Where It Happens", artist: "Leslie Odom Jr.", movie: "Hamilton", year: 2020, hint: "Burr wants to be in decision making." },
    { title: "Do You Hear the People Sing?", artist: "Les Misérables Cast", movie: "Les Misérables", year: 2012, hint: "French students build a barricade." },
    { title: "I Dreamed a Dream", artist: "Anne Hathaway", movie: "Les Misérables", year: 2012, hint: "Fantine loses her factory job." },
    { title: "One Day More", artist: "Les Misérables Cast", movie: "Les Misérables", year: 2012, hint: "Characters prepare for tomorrow's revolution." },
    { title: "Seasons of Love", artist: "Rent Cast", movie: "Rent", year: 2005, hint: "525,600 minutes measure a year." },
    { title: "La Vie Bohème", artist: "Rent Cast", movie: "Rent", year: 2005, hint: "Artists celebrate bohemian life in cafe." },
    { title: "The Phantom of the Opera", artist: "Gerard Butler", movie: "The Phantom of the Opera", year: 2004, hint: "Disfigured genius haunts opera house." },
    { title: "Music of the Night", artist: "Gerard Butler", movie: "The Phantom of the Opera", year: 2004, hint: "Christine taken to underground lair." },
    { title: "Come What May", artist: "Ewan McGregor & Nicole Kidman", movie: "Moulin Rouge!", year: 2001, hint: "Secret love song in elephant room." },
    { title: "El Tango de Roxanne", artist: "Ewan McGregor", movie: "Moulin Rouge!", year: 2001, hint: "Jealousy tango in Parisian nightclub." },
    { title: "Dancing Queen", artist: "Meryl Streep", movie: "Mamma Mia!", year: 2008, hint: "Women dance on Greek island dock." },
    { title: "Mamma Mia", artist: "Meryl Streep", movie: "Mamma Mia!", year: 2008, hint: "Donna discovers three ex-lovers arrived." },
    { title: "You Can't Stop the Beat", artist: "Nikki Blonsky", movie: "Hairspray", year: 2007, hint: "Tracy integrates the Corny Collins Show." },
    { title: "Good Morning Baltimore", artist: "Nikki Blonsky", movie: "Hairspray", year: 2007, hint: "Teen loves her city despite rats." },
    { title: "Don't Rain on My Parade", artist: "Barbra Streisand", movie: "Funny Girl", year: 1968, hint: "Fanny Brice chases Nick to tugboat." },
    { title: "Cabaret", artist: "Liza Minnelli", movie: "Cabaret", year: 1972, hint: "Sally Bowles performs in Kit Kat Klub." },
    { title: "Cell Block Tango", artist: "Catherine Zeta-Jones", movie: "Chicago", year: 2002, hint: "Six murderesses share their stories." },
    { title: "Razzle Dazzle", artist: "Richard Gere", movie: "Chicago", year: 2002, hint: "Lawyer turns trial into circus." },
    { title: "The Greatest Show", artist: "Hugh Jackman", movie: "The Greatest Showman", year: 2017, hint: "Barnum starts a circus spectacle." },
    { title: "This Is Me", artist: "Keala Settle", movie: "The Greatest Showman", year: 2017, hint: "Bearded lady leads oddities anthem." },
    { title: "Rewrite the Stars", artist: "Zac Efron & Zendaya", movie: "The Greatest Showman", year: 2017, hint: "Trapeze artists fall in love." },
    { title: "America", artist: "Rita Moreno", movie: "West Side Story", year: 1961, hint: "Sharks argue about life in USA." },
    { title: "Tonight", artist: "Natalie Wood", movie: "West Side Story", year: 1961, hint: "Tony and Maria on fire escape." },
    { title: "Suddenly, Seymour", artist: "Rick Moranis", movie: "Little Shop of Horrors", year: 1986, hint: "Nerd comforts Audrey in skid row." },
    { title: "Dentist!", artist: "Steve Martin", movie: "Little Shop of Horrors", year: 1986, hint: "Sadistic dentist loves causing pain." },
    { title: "Don't Cry for Me Argentina", artist: "Madonna", movie: "Evita", year: 1996, hint: "Eva Peron addresses crowd from balcony." },
    { title: "And I Am Telling You I'm Not Going", artist: "Jennifer Hudson", movie: "Dreamgirls", year: 2006, hint: "Effie refuses to leave the group." },
    { title: "Luck Be a Lady", artist: "Marlon Brando", movie: "Guys and Dolls", year: 1955, hint: "Sky Masterson gambles in sewer." },
    { title: "I Could Have Danced All Night", artist: "Audrey Hepburn", movie: "My Fair Lady", year: 1964, hint: "Eliza finally pronounces rain correctly." },
    { title: "If I Were a Rich Man", artist: "Topol", movie: "Fiddler on the Roof", year: 1971, hint: "Milkman dreams of wealth in barn." },
    { title: "Hello, Dolly!", artist: "Barbra Streisand", movie: "Hello, Dolly!", year: 1969, hint: "Matchmaker returns to Harmonia Gardens." },
    { title: "Consider Yourself", artist: "Jack Wild", movie: "Oliver!", year: 1968, hint: "Pickpockets welcome orphan to London." },
    { title: "Superstar", artist: "Carl Anderson", movie: "Jesus Christ Superstar", year: 1973, hint: "Judas questions Jesus's fame." },
    { title: "The Worst Pies in London", artist: "Helena Bonham Carter", movie: "Sweeney Todd: The Demon Barber of Fleet Street", year: 2007, hint: "Mrs. Lovett bakes with bad meat." },
    { title: "Agony", artist: "Chris Pine", movie: "Into the Woods", year: 2014, hint: "Princes complain about elusive cinderellas." },
    { title: "Cups", artist: "Anna Kendrick", movie: "Pitch Perfect", year: 2012, hint: "Kendrick auditions with a cup." },
    { title: "Seventy-Six Trombones", artist: "Robert Preston", movie: "The Music Man", year: 1962, hint: "Con man organizes boys' marching band." }
  ]
};